
import React from 'react';
function welcome() {
  return <>
    <div className="visa-global-heading-1">Características y condiciones de la visa electrónica para emitir una visa electrónica</div>
    <ul className="visa-global-ul-1">
    <li><p> <span> Una visa electrónica para ingresar al Distrito Federal del Lejano Oriente solo puede ser obtenida por ciudadanos de los siguientes estados, listados por el Gobierno de la Federación de Rusia. </span> </p> </ li>
    <li><p> <span> Una visa electrónica para ingresar al Óblast de Kaliningrado solo puede ser obtenida por nacionales de los países enumerados por el Gobierno de la Federación de Rusia. </span> </p> </li>
    <li><p> <span> Una visa electrónica para ingresar a San Petersburgo y Leningrado Oblast solo puede ser obtenida por nacionales de los países enumerados por el Gobierno de la Federación de Rusia. </span> </p> </ li >
    <li><p> <span> Una visa electrónica es gratis. No se requieren invitaciones, confirmaciones de reserva de hotel o cualquier otro documento que confirme el propósito de su viaje a la Federación Rusa para una visa electrónica. El período de tiempo para emitir una visa electrónica no es más de 4 días calendario a partir de la fecha de presentación de la solicitud completa. </span> </p> </li>
    <li><p> <span> La visa electrónica se puede utilizar para ingresar y salir de la Federación Rusa en los siguientes puntos de control en la frontera nacional de la Federación Rusa en el Distrito Federal del Lejano Oriente, Óblast de Kaliningrado, San Petersburgo y Óblast de Leningrado : </span> </p> </li>
    <li><p> <span> La visa electrónica es una visa de entrada única y se emite por 30 días calendario a partir de la fecha de su emisión. La estadía permitida en la Federación Rusa con una visa electrónica es de hasta 8 días a partir de la fecha de entrada, dentro de su período de validez. La validez de la visa electrónica y / o la estadía permitida no se puede extender. </span> </p> </li>
    <br/>
    <strong> ¡ATENCIÓN! </strong> El período permitido de estadía en la Federación Rusa de hasta 8 días bajo una visa electrónica no implica que uno pueda permanecer durante las 192 horas completas (24 horas multiplicadas por 8). El período de estadía en la Federación de Rusia siempre comienza a la medianoche del día del pasaje a través del control de pasaportes al ingresar, independientemente de la hora real del pasaje a través del control de pasaportes. Por ejemplo, tiene una visa electrónica válida del 15 de julio al 13 de agosto y pasa el control de pasaportes al ingresar a las 8:00 pm del lunes 1 de agosto. En ese caso, debe pasar el control de pasaportes al salir hasta las 11:59 p. M. Del lunes 8 de agosto (en lugar de hasta las 8:00 p. M. Del martes 9 de agosto). También debe tener en cuenta que si pasó el control de pasaportes al ingresar, por ejemplo, el 10 de agosto con la visa electrónica mencionada en el ejemplo anterior, debe pasar el control de pasaportes al salir hasta las 11:59 p.m. del 13 de agosto, es decir hasta que expire la visa electrónica.
    <br/> <br/>
    <li><p> <span> Las visas electrónicas pueden ser solo de las siguientes categorías: visa de negocios ordinaria (el propósito del viaje es comercial), visa de turista ordinaria (el propósito del viaje es turismo) y visa humanitaria ordinaria (propósitos del viaje son lazos deportivos, culturales, científicos y tecnológicos). Si el propósito de su viaje a la Federación de Rusia no corresponde a ninguno de los anteriores, debe solicitar una visa tradicional (no electrónica) en una misión diplomática u oficina consular de la Federación de Rusia. </span> </p> </li>
    <li><p> <span> Los ciudadanos extranjeros que han llegado a la Federación Rusa con visas electrónicas tienen derecho a la libertad de movimiento dentro del territorio de la entidad constitutiva de la Federación Rusa a la que ingresaron, con la excepción de los territorios, organizaciones e instalaciones, para ingresar que requieren un permiso especial de acuerdo con las leyes federales de la Federación Rusa. Los ciudadanos extranjeros deben abandonar el territorio de la Federación de Rusia solo a través de los puntos de control de la entidad constitutiva de la Federación de Rusia a la que ingresaron. </span> </p> </li>
    <li><p> <span> Puede completar un formulario de solicitud para una visa electrónica en este sitio web a más tardar 20 días y no más tarde de 4 días antes de la fecha prevista de entrada en la Federación de Rusia. </span> </p> </li>
    <li><p> <span> Su pasaporte debe ser válido por al menos 6 meses a partir de la fecha en que solicitó una visa electrónica. Su pasaporte debe tener espacio libre para los sellos de cruce de fronteras. </span> </p> </li>
    <li><p> <span> Los ciudadanos extranjeros que han llegado a la Federación Rusa con visas electrónicas deben tener un seguro médico válido en el territorio de la Federación Rusa durante todo el período de estancia. </span> </p> </li>
    <li><p> <span> No es necesario solicitar una visa electrónica para ingresar al Distrito Federal del Lejano Oriente, el Óblast de Kaliningrado, San Petersburgo y el Óblast de Leningrado si ya tiene una visa rusa válida en su pasaporte. Se le permite ingresar a dichas regiones utilizando una visa regular dentro de su período de validez sin limitaciones previstas por una visa electrónica. Una visa electrónica no extiende el período de validez de una visa regular. </span> </p> </li>
    <li><p> <span> Antes de solicitar una visa electrónica, debe aceptar el procesamiento, la transferencia y el almacenamiento automáticos de los datos proporcionados en su solicitud a los fines de la emisión de la visa electrónica. </span> </p> </li>
    <li><p> <span> Su aplicación debe contener datos completos y válidos. Cualquier información incorrecta, incluidos los datos del pasaporte y la foto, podría causar el rechazo de la visa o la revocación de una visa ya emitida en el punto de control fronterizo nacional de la Federación de Rusia. </span> </p> </li>
    </ul>
  </>
}
export default welcome;