
import React from 'react';
function welcome() {
  return <>
    <div className="visa-global-heading-1">Caractéristiques du visa électronique et conditions de délivrance d'un visa électronique</div>
    <ul className="visa-global-ul-1">
    <li> <p> <span> Un visa électronique pour entrer dans le district fédéral d'Extrême-Orient ne peut être obtenu que par des ressortissants des États suivants répertoriés par le gouvernement de la Fédération de Russie. </ span> </ p> </ li>
    <li> <p> <span> Un visa électronique pour entrer dans l'oblast de Kaliningrad ne peut être obtenu que par des ressortissants des pays énumérés par le gouvernement de la Fédération de Russie. </ span> </ p> </ li>
    <li> <p> <span> Un visa électronique pour entrer dans Saint-Pétersbourg et dans l'oblast de Léningrad ne peut être obtenu que par des ressortissants des pays énumérés par le gouvernement de la Fédération de Russie. </ span> </ p> </ li >
    <li> <p> <span> Un visa électronique est gratuit. Les invitations, les confirmations de réservation d'hôtel ou tout autre document confirmant le but de votre voyage en Russie ne sont pas requis pour un visa électronique. Le délai de délivrance d'un visa électronique ne dépasse pas 4 jours calendaires à compter de la date de soumission de la demande complète. </span> </ p> </ li>
    <li> <p> <span> Le visa électronique peut être utilisé pour entrer et sortir de la Fédération de Russie aux points de contrôle suivants situés à la frontière nationale de la Fédération de Russie dans le district fédéral extrême-oriental, les oblasts de Kaliningrad, Saint-Pétersbourg et Léningrad. : </ span> </ p> </ li>
    <li> <p> <span> Le visa électronique est un visa à entrée unique et est délivré pour une période de 30 jours calendrier à compter de la date de son émission. Le séjour autorisé dans la Fédération de Russie avec un visa électronique peut aller jusqu'à 8 jours à compter de la date d'entrée dans le délai de validité. La validité du visa électronique et / ou le séjour autorisé ne peuvent pas être prolongés. </ span> </ p> </ li>
    <br/>
    <strong> ATTENTION! </ strong> La durée de séjour autorisée dans un pays membre de la Fédération de Russie allant jusqu'à 8 jours avec un e-visa n'implique pas qu'une personne puisse rester 192 heures au total (24 heures multipliées par 8). La période de séjour dans la Fédération de Russie commence toujours à minuit le jour du passage sous le contrôle des passeports à l’entrée, quelle que soit l’heure réelle du passage sous le contrôle des passeports. Par exemple, vous avez un e-visa valide du 15 juillet au 13 août et vous passez le contrôle des passeports dès votre entrée le lundi 1 er août à 20 heures. Dans ce cas, vous devez passer le contrôle des passeports lors de la sortie jusqu'à 23h59 le lundi 8 août (plutôt que jusqu'à 20 heures le mardi 9 août). Vous devez également noter que si vous passez le contrôle des passeports lors de l'entrée, par exemple le 10 août avec le visa électronique mentionné dans l'exemple ci-dessus, vous devez passer le contrôle des passeports à la sortie jusqu'au 13 août à 23h59, c'est-à-dire jusqu'à l'expiration du e-visa.
    <br/> <br/>
    <li> <p> <span> Les visas électroniques peuvent appartenir aux catégories suivantes: visa d'affaires ordinaire (le but du voyage est un voyage d'affaires), visa de touriste ordinaire (le but est un voyage touristique) et le visa humanitaire ordinaire (le but d'un voyage) sont des liens sportifs, culturels, scientifiques et technologiques). Si le but de votre voyage en Fédération de Russie ne correspond à aucun de ces éléments, vous devez demander un visa traditionnel (non électronique) auprès d'une mission diplomatique ou d'un consulat de la Fédération de Russie. </ span> </ p> </ li>
    <li> <p> <span> Les ressortissants étrangers qui sont arrivés dans la Fédération de Russie avec un visa électronique ont le droit de circuler librement sur le territoire de l'entité constitutive de la Fédération de Russie où ils sont entrés, à l'exception des territoires, organisations et installations, pour lesquelles une autorisation spéciale est requise conformément aux lois fédérales de la Fédération de Russie. Les citoyens étrangers ne doivent quitter le territoire de la Fédération de Russie que par les points de contrôle de l'entité constitutive de la Fédération de Russie dans laquelle ils sont entrés. </ span> </ p> </ li>
    <li> <p> <span> Vous pouvez remplir un formulaire de demande de visa électronique sur ce site web au plus tôt 20 jours et au plus tard 4 jours avant la date prévue pour l'entrée dans la Fédération de Russie. </ span> </ p> </ li>
    <li> <p> <span> Votre passeport doit être valide pendant au moins 6 mois à compter de la date à laquelle vous avez demandé un visa électronique. Votre passeport doit disposer d'un espace libre pour les timbres de passage des frontières. </ span> </ p> </ li>
    <li> <p> <span> Les ressortissants étrangers qui sont arrivés dans la Fédération de Russie avec un visa électronique doivent être en possession d'une assurance maladie valide sur le territoire de la Fédération de Russie pour toute la durée de leur séjour. </ span> </ p> </ li>
    <li> <p> <span> Il n'est pas nécessaire de demander un visa électronique pour entrer dans le district fédéral d'Extrême-Orient, dans l'oblast de Kaliningrad, à Saint-Pétersbourg et dans l'oblast de Léningrad si votre passeport est déjà valide. Vous êtes autorisé à entrer dans lesdites régions en utilisant un visa régulier pendant sa période de validité, sans aucune limitation prévue par un visa électronique. Un visa électronique ne prolonge pas la durée de validité d'un visa régulier. </ span> </ p> </ li>
    <li> <p> <span> Avant de demander un visa électronique, vous devez accepter le traitement, le transfert et le stockage automatiques des données fournies dans votre demande aux fins de la délivrance du visa électronique. </ span> </ p> </ li>
    <li> <p> <span> Votre application doit contenir des données complètes et valides. Toute information incorrecte, y compris les données de passeport et la photo, pourrait entraîner le rejet du visa ou la révocation d'un visa déjà délivré au poste de contrôle aux frontières de la Fédération de Russie. </ span> </ p> </ li>
    </ ul>
  </>
}
export default welcome;