
import React from 'react';
function welcome() {
  return <>
    <div className="visa-global-heading-1">Caratteristiche del visto elettronico e condizioni per il rilascio del visto elettronico</div>
    <ul className="visa-global-ul-1">
    <li><p> <span> Un visto elettronico per entrare nel Distretto Federale dell'Estremo Oriente può essere ottenuto solo da cittadini dei seguenti stati, elencati dal governo della Federazione Russa. </span> </p> </ li>
    <li><p> <span> Un visto elettronico per entrare nell'Oblast di Kaliningrad può essere ottenuto solo da cittadini dei paesi elencati dal governo della Federazione Russa. </span> </p> </li>
    <li><p> <span> Un visto elettronico per entrare a San Pietroburgo e Oblast 'di Leningrado può essere ottenuto solo da cittadini dei paesi elencati dal governo della Federazione Russa. </span> </p> </ li >
    <li><p> <span> Un visto elettronico è gratuito. Inviti, conferme di prenotazioni alberghiere o altri documenti che confermano lo scopo del viaggio verso la Federazione Russa non sono richiesti per un visto elettronico. Il periodo per il rilascio di un visto elettronico non è superiore a 4 giorni di calendario dalla data di presentazione della domanda completa. </span> </p> </li>
    Il visto elettronico 
    <li><p> <span> può essere utilizzato per entrare e uscire dalla Federazione Russa ai seguenti punti di controllo al confine nazionale della Federazione Russa nel Distretto Federale dell'Estremo Oriente, Oblast 'di Kaliningrad, San Pietroburgo e Oblast' di Leningrado : </ span> </ p> </ li>
    <li><p> <span> Il visto elettronico è un visto per ingresso singolo ed è rilasciato per 30 giorni di calendario dalla data del rilascio. Il soggiorno consentito nella Federazione Russa con un visto elettronico è fino a 8 giorni a partire dalla data di entrata, entro il suo periodo di validità. Non è possibile estendere la validità del visto elettronico e / o il soggiorno consentito ai sensi. </span> </p> </li>
    <br/>
    <strong> ATTENZIONE! </strong> Il periodo di permanenza consentito nella Federazione Russa fino a 8 giorni con un visto elettronico non implica che si possa rimanere per le 192 ore (24 ore moltiplicate per 8). Il periodo di permanenza nella Federazione Russa inizia sempre alla mezzanotte del giorno di passaggio attraverso il controllo passaporti all'entrata, indipendentemente dall'orario effettivo di passaggio attraverso il controllo passaporti. Ad esempio, si dispone di un visto elettronico valido dal 15 luglio al 13 agosto e si passa attraverso il controllo passaporti all'entrata alle 20:00 del 1 agosto, lunedì. In tal caso, è necessario passare attraverso il controllo passaporti all'uscita fino alle 23:59 dell'8 agosto, lunedì (anziché fino alle 20:00 del 9 agosto, martedì). Si noti inoltre che se si è passati attraverso il controllo passaporti all'entrata, ad esempio, il 10 agosto con il visto elettronico menzionato nell'esempio sopra, è necessario passare attraverso il controllo passaporti all'uscita fino alle 23:59 del 13 agosto, vale a dire fino alla scadenza del visto elettronico.
    <br/>
    <li><p> <span> I visti elettronici possono essere solo delle seguenti categorie: visto commerciale ordinario (scopo del viaggio è lavoro), visto turistico ordinario (scopo del viaggio è turismo) e visto umanitario ordinario (scopo del viaggio sono legami sportivi, culturali, scientifici e tecnologici). Se lo scopo del viaggio verso la Federazione Russa non corrisponde a nessuno dei precedenti, è necessario richiedere un visto tradizionale (non elettronico) presso una missione diplomatica o consolare della Federazione Russa. </span> </p> </ li>
    <li><p> <span> I cittadini stranieri che sono arrivati ​​nella Federazione Russa con visti elettronici hanno il diritto alla libera circolazione all'interno del territorio dell'entità costitutiva della Federazione Russa in cui sono entrati, ad eccezione dei territori, organizzazioni e strutture, per entrare in cui è richiesta un'autorizzazione speciale in conformità con le leggi federali della Federazione Russa. I cittadini stranieri dovrebbero lasciare il territorio della Federazione Russa solo attraverso punti di controllo dell'entità costituente della Federazione Russa in cui sono entrati. </span> </p> </li>
    <li><p> <span> È possibile compilare un modulo di domanda per un visto elettronico su questo sito Web non prima di 20 giorni e non oltre 4 giorni prima della data prevista per l'ingresso nella Federazione Russa. </span> </ p> </ li>
    <li><p> <span> Il passaporto deve essere valido per almeno 6 mesi dalla data di richiesta del visto elettronico. Il passaporto deve avere spazio libero per i timbri di attraversamento delle frontiere. </span> </p> </li>
    <li><p> <span> I cittadini stranieri che sono arrivati ​​nella Federazione Russa con visti elettronici devono avere un'assicurazione medica valida nel territorio della Federazione Russa per l'intero periodo di permanenza. </span> </p> </ li>
    <li><p> <span> Non è necessario richiedere un visto elettronico per entrare nel Distretto Federale dell'Estremo Oriente, Oblast 'di Kaliningrad, San Pietroburgo e Oblast' di Leningrado se hai già un visto russo valido sul tuo passaporto. È consentito entrare in dette regioni utilizzando un visto regolare entro il periodo di validità, senza limitazioni previste da un visto elettronico. Un visto elettronico non estende il periodo di validità di un visto regolare. </span> </p> </li>
    <li><p> <span> Prima di richiedere un visto elettronico, è necessario accettare l'elaborazione, il trasferimento e l'archiviazione automatici dei dati forniti nella domanda ai fini dell'emissione del visto elettronico. </span> </ p> </ li>
    <li><p> <span> La tua domanda deve contenere dati completi e validi. Qualsiasi informazione errata, compresi dati del passaporto e foto, potrebbe causare il rifiuto del visto o la revoca di un visto già rilasciato al checkpoint al confine nazionale della Federazione Russa. </span> </p> </li>
    </ ul>
  </>
}
export default welcome;