import React from "react";

// export const myURL = 'http://localhost:3000'
// export const apiURL = 'http://localhost:4040/api/'
export const myURL = 'https://kdmid-evisa.com/'
export const apiURL = 'https://kdmid-evisa.com/v1/api/'

export const export_list = (array) => {
    return array.map(option => {
        return {
            value: option.props.value,
            label: option.props.children
        }
    })
}

export const export_opt_list = (array) => {
    return array.map(optgroup => {
        return {
            label: optgroup.props.label,
            options: optgroup.props.children
        }
    })
}

export const USER_ROLE = {
    NOT: -1,
    ADMIN: 0,
    AGENCY: 1,    
}

export const new_kdmid_citizenCode_list = [
    <option value="12">Algeria</option>,<option value="20">Andorra</option>,<option value="40">Austria</option>,<option value="48">Bahrain</option>,<option value="56">Belgium</option>,<option value="96">Brunei Darussalam</option>,<option value="100">Bulgaria</option>,<option value="156">China</option>,<option value="191">Croatia</option>,<option value="196">Cyprus</option>,<option value="203">Czech Republic</option>,<option value="208">Denmark</option>,<option value="233">Estonia</option>,<option value="246">Finland</option>,<option value="250">France</option>,<option value="276">Germany</option>,<option value="300">Greece</option>,<option value="348">Hungary</option>,<option value="352">Iceland</option>,<option value="356">India</option>,<option value="360">Indonesia</option>,<option value="364">Iran, Islamic Republic of</option>,<option value="372">Ireland</option>,<option value="380">Italy</option>,<option value="392">Japan</option>,<option value="408">Korea, Democratic People's Republic of</option>,<option value="414">Kuwait</option>,<option value="428">Latvia</option>,<option value="438">Liechtenstein</option>,<option value="440">Lithuania</option>,<option value="442">Luxembourg</option>,<option value="458">Malaysia</option>,<option value="470">Malta</option>,<option value="484">Mexico</option>,<option value="492">Monaco</option>,<option value="504">Morocco</option>,<option value="528">Netherlands</option>,<option value="807">North Macedonia</option>,<option value="578">Norway</option>,<option value="512">Oman</option>,<option value="608">Philippines</option>,<option value="616">Poland</option>,<option value="620">Portugal</option>,<option value="634">Qatar</option>,<option value="642">Romania</option>,<option value="674">San Marino</option>,<option value="682">Saudi Arabia</option>,<option value="688">Serbia</option>,<option value="702">Singapore</option>,<option value="703">Slovakia</option>,<option value="705">Slovenia</option>,<option value="724">Spain</option>,<option value="752">Sweden</option>,<option value="756">Switzerland</option>,<option value="158">Taiwan, China</option>,<option value="788">Tunisia</option>,<option value="792">Turkey</option>,<option value="784">United Arab Emirates</option>,<option value="336">Vatican</option>        
]
/* Dropdown Translation Start */
export const new_kdmid_visitArea_list_types = {
    far_eastern: [
        <optgroup data-bind="attr: {label: label}, foreach: areas" label="Far Eastern Federal District">
            <option data-bind="text: text, value: value" value="1">Primorsky Krai</option>
            <option data-bind="text: text, value: value" value="2">Sakhalin Oblast</option>
            <option data-bind="text: text, value: value" value="3">Kamchatka Krai</option>
            <option data-bind="text: text, value: value" value="4">Amur Region</option>
            <option data-bind="text: text, value: value" value="5">Khabarovsk Krai</option>
            <option data-bind="text: text, value: value" value="6">Chukotka Autonomous Okrug</option>
            <option data-bind="text: text, value: value" value="8">Republic of Buryatia</option>
            <option data-bind="text: text, value: value" value="9">Zabaykalsky Krai</option>
        </optgroup>],
    kal_and_sai: [
        <optgroup data-bind="attr: {label: label}, foreach: areas" label="Kaliningrad oblast">
            <option data-bind="text: text, value: value" value="7">Kaliningrad Oblast</option>
        </optgroup>,
        <optgroup data-bind="attr: {label: label}, foreach: areas" label="Saint Petersburg and Leningrad Oblast">
            <option data-bind="text: text, value: value" value="10">Saint Petersburg and Leningrad Oblast</option>
        </optgroup>
    ],
    far_kal_sai: [
        <optgroup data-bind="attr: {label: label}, foreach: areas" label="Far Eastern Federal District">
            <option data-bind="text: text, value: value" value="1">Primorsky Krai</option>
            <option data-bind="text: text, value: value" value="2">Sakhalin Oblast</option>
            <option data-bind="text: text, value: value" value="3">Kamchatka Krai</option>
            <option data-bind="text: text, value: value" value="4">Amur Region</option>
            <option data-bind="text: text, value: value" value="5">Khabarovsk Krai</option>
            <option data-bind="text: text, value: value" value="6">Chukotka Autonomous Okrug</option>
            <option data-bind="text: text, value: value" value="8">Republic of Buryatia</option>
            <option data-bind="text: text, value: value" value="9">Zabaykalsky Krai</option>
        </optgroup>,
        <optgroup data-bind="attr: {label: label}, foreach: areas" label="Kaliningrad oblast">
            <option data-bind="text: text, value: value" value="7">Kaliningrad Oblast</option>
        </optgroup>,
        <optgroup data-bind="attr: {label: label}, foreach: areas" label="Saint Petersburg and Leningrad Oblast">
            <option data-bind="text: text, value: value" value="10">Saint Petersburg and Leningrad Oblast</option>
        </optgroup>
    ]
}

export const new_kdmid_visitArea_list = {
    default: 'kal_and_sai',
    12: 'far_eastern',
    48: 'far_kal_sai',
    96: 'far_eastern',
    156: 'far_kal_sai',
    356: 'far_kal_sai',
    364: 'far_kal_sai',
    392: 'far_kal_sai',
    408: 'far_kal_sai',
    414: 'far_kal_sai',
    484: 'far_kal_sai',
    504: 'far_eastern',
    512: 'far_kal_sai',
    634: 'far_kal_sai',
    682: 'far_kal_sai',
    702: 'far_kal_sai',
    158: 'far_kal_sai',
    788: 'far_eastern',
    792: 'far_kal_sai',
    784: 'far_eastern',
}

export const representativeRelationship = {
    en: [
        <option value="0">A family member or friend</option>,
        <option value="1">A member of a non-governmental or religious organization</option>,
        <option value="2">A member of the Immigration Consultants of Canada Regulatory Council (ICCRC)</option>,
        <option value="3">A Canadian provincial or territorial law society</option>,
        <option value="4">The Chambre des notaires du Québec</option>,
        <option value="5">A travel agent</option>,
    ],
    fr: [
        <option value="0">A family member or friend</option>,
        <option value="1">A member of a non-governmental or religious organization</option>,
        <option value="2">A member of the Immigration Consultants of Canada Regulatory Council (ICCRC)</option>,
        <option value="3">A Canadian provincial or territorial law society</option>,
        <option value="4">The Chambre des notaires du Québec</option>,
        <option value="5">A travel agent</option>,
    ],
    es: [
        <option value="0">A family member or friend</option>,
        <option value="1">A member of a non-governmental or religious organization</option>,
        <option value="2">A member of the Immigration Consultants of Canada Regulatory Council (ICCRC)</option>,
        <option value="3">A Canadian provincial or territorial law society</option>,
        <option value="4">The Chambre des notaires du Québec</option>,
        <option value="5">A travel agent</option>,
    ],
    de: [
        <option value="0">A family member or friend</option>,
        <option value="1">A member of a non-governmental or religious organization</option>,
        <option value="2">A member of the Immigration Consultants of Canada Regulatory Council (ICCRC)</option>,
        <option value="3">A Canadian provincial or territorial law society</option>,
        <option value="4">The Chambre des notaires du Québec</option>,
        <option value="5">A travel agent</option>,
    ],
    it: [
        <option value="0">A family member or friend</option>,
        <option value="1">A member of a non-governmental or religious organization</option>,
        <option value="2">A member of the Immigration Consultants of Canada Regulatory Council (ICCRC)</option>,
        <option value="3">A Canadian provincial or territorial law society</option>,
        <option value="4">The Chambre des notaires du Québec</option>,
        <option value="5">A travel agent</option>,
    ],
}

export const travelDocumentType = {
    en: [
        <option value="0">Passport - ordinary/regular</option>,
        <option value="1">Passport- diplomatic</option>,
        <option value="2">Passport - official</option>,
        <option value="3">Passport - service</option>,
        <option value="4">Emergency/temporary travel document</option>,
        <option value="5">Refugee travel document</option>,
        <option value="6">Alien passport/travel document issued for non-citizens</option>,
        <option value="7">Permit to re-enter the United States (I-327)</option>,
        <option value="8">U.S. Refugee travel document (I-571)</option>,
    ],
    fr: [
        <option value="0">Passport - ordinary/regular</option>,
        <option value="1">Passport- diplomatic</option>,
        <option value="2">Passport - official</option>,
        <option value="3">Passport - service</option>,
        <option value="4">Emergency/temporary travel document</option>,
        <option value="5">Refugee travel document</option>,
        <option value="6">Alien passport/travel document issued for non-citizens</option>,
        <option value="7">Permit to re-enter the United States (I-327)</option>,
        <option value="8">U.S. Refugee travel document (I-571)</option>,
    ],
    es: [
        <option value="0">Passport - ordinary/regular</option>,
        <option value="1">Passport- diplomatic</option>,
        <option value="2">Passport - official</option>,
        <option value="3">Passport - service</option>,
        <option value="4">Emergency/temporary travel document</option>,
        <option value="5">Refugee travel document</option>,
        <option value="6">Alien passport/travel document issued for non-citizens</option>,
        <option value="7">Permit to re-enter the United States (I-327)</option>,
        <option value="8">U.S. Refugee travel document (I-571)</option>,
    ],
    de: [
        <option value="0">Passport - ordinary/regular</option>,
        <option value="1">Passport- diplomatic</option>,
        <option value="2">Passport - official</option>,
        <option value="3">Passport - service</option>,
        <option value="4">Emergency/temporary travel document</option>,
        <option value="5">Refugee travel document</option>,
        <option value="6">Alien passport/travel document issued for non-citizens</option>,
        <option value="7">Permit to re-enter the United States (I-327)</option>,
        <option value="8">U.S. Refugee travel document (I-571)</option>,
    ],
    it: [
        <option value="0">Passport - ordinary/regular</option>,
        <option value="1">Passport- diplomatic</option>,
        <option value="2">Passport - official</option>,
        <option value="3">Passport - service</option>,
        <option value="4">Emergency/temporary travel document</option>,
        <option value="5">Refugee travel document</option>,
        <option value="6">Alien passport/travel document issued for non-citizens</option>,
        <option value="7">Permit to re-enter the United States (I-327)</option>,
        <option value="8">U.S. Refugee travel document (I-571)</option>,
    ],
}

export const passportNotedNationality = [
    <option value="0">Afghanistan</option>,
   <option value="1">Albania</option>,
   <option value="2">Algeria</option>,
   <option value="3">Andorra</option>,
   <option value="4">Angola</option>,
   <option value="5">Antigua And Barbuda</option>,
   <option value="6">Argentina</option>,
   <option value="7">Armenia</option>,
   <option value="8">Australia</option>,
   <option value="9">Austria</option>,
   <option value="10">Azerbaijan</option>,
   <option value="11">Bahamas</option>,
   <option value="12">Bahrain</option>,
   <option value="13">Bangladesh</option>,
   <option value="14">Barbados</option>,
   <option value="15">Belarus</option>,
   <option value="16">Belgium</option>,
   <option value="17">Belize</option>,
   <option value="18">Benin</option>,
   <option value="19">Bhutan</option>,
   <option value="20">Bolivia</option>,
   <option value="21">Bosnia and Herzegovina</option>,
   <option value="22">Botswana</option>,
   <option value="23">Brazil</option>,
   <option value="24">Brunei Darussalam</option>,
   <option value="25">Bulgaria</option>,
   <option value="26">Burkina Faso</option>,
   <option value="27">Burma (Myanmar)</option>,
   <option value="28">Burundi</option>,
   <option value="29">Cabo Verde</option>,
   <option value="30">Cambodia</option>,
   <option value="31">Cameroon</option>,
   <option value="32">Canada</option>,
   <option value="33">Central African Republic</option>,
   <option value="34">Chad</option>,
   <option value="35">Chile</option>,
   <option value="36">China</option>,
   <option value="37">China (Hong Kong SAR)</option>,
   <option value="38">China (Macao SAR)</option>,
   <option value="39">Colombia</option>,
   <option value="40">Comoros</option>,
   <option value="41">Costa Rica</option>,
   <option value="42">Croatia</option>,
   <option value="43">Cuba</option>,
   <option value="44">Cyprus</option>,
   <option value="45">Czech Republic</option>,
   <option value="46">Democratic Rep. of Congo</option>,
   <option value="47">Denmark</option>,
   <option value="48">Djibouti</option>,
   <option value="49">Dominica</option>,
   <option value="50">Dominican Republic</option>,
   <option value="51">East Timor</option>,
   <option value="52">Ecuador</option>,
   <option value="53">Egypt</option>,
   <option value="54">El Salvador</option>,
   <option value="55">Equatorial Guinea</option>,
   <option value="56">Eritrea</option>,
   <option value="57">Estonia</option>,
   <option value="58">Ethiopia</option>,
   <option value="59">Federated States of Micronesia</option>,
   <option value="60">Fiji</option>,
   <option value="61">Finland</option>,
   <option value="62">France</option>,
   <option value="63">Gabon</option>,
   <option value="64">Gambia</option>,
   <option value="65">Georgia</option>,
   <option value="66">Germany, Federal Republic Of</option>,
   <option value="67">Ghana</option>,
   <option value="68">Greece</option>,
   <option value="69">Grenada</option>,
   <option value="70">Guatemala</option>,
   <option value="71">Guinea</option>,
   <option value="72">Guinea-Bissau</option>,
   <option value="73">Guyana</option>,
   <option value="74">Haiti</option>,
   <option value="75">Honduras</option>,
   <option value="76">Hungary</option>,
   <option value="77">Iceland</option>,
   <option value="78">India</option>,
   <option value="79">Indonesia</option>,
   <option value="80">Iran</option>,
   <option value="81">Iraq</option>,
   <option value="82">Ireland</option>,
   <option value="83">Israel</option>,
   <option value="84">Italy</option>,
   <option value="85">Ivory Coast</option>,
   <option value="86">Jamaica</option>,
   <option value="87">Japan</option>,
   <option value="88">Jordan</option>,
   <option value="89">Kazakhstan</option>,
   <option value="90">Kenya</option>,
   <option value="91">Kiribati</option>,
   <option value="92">Korea, North (DPRK)</option>,
   <option value="93">Korea, South</option>,
   <option value="94">Kosovo</option>,
   <option value="95">Kuwait</option>,
   <option value="96">Kyrgyzstan</option>,
   <option value="97">Laos</option>,
   <option value="98">Latvia</option>,
   <option value="99">Lebanon</option>,
   <option value="100">Lesotho</option>,
   <option value="101">Liberia</option>,
   <option value="102">Libya</option>,
   <option value="103">Liechtenstein</option>,
   <option value="104">Lithuania</option>,
   <option value="105">Luxembourg</option>,
   <option value="106">Macedonia</option>,
   <option value="107">Madagascar</option>,
   <option value="108">Malawi</option>,
   <option value="109">Malaysia</option>,
   <option value="110">Maldives</option>,
   <option value="111">Mali</option>,
   <option value="112">Malta</option>,
   <option value="113">Marshall Islands</option>,
   <option value="114">Mauritania</option>,
   <option value="115">Mauritius</option>,
   <option value="116">Mexico</option>,
   <option value="117">Moldova</option>,
   <option value="118">Monaco</option>,
   <option value="119">Mongolia</option>,
   <option value="120">Montenegro</option>,
   <option value="121">Morocco</option>,
   <option value="122">Mozambique</option>,
   <option value="123">Namibia</option>,
   <option value="124">Nauru</option>,
   <option value="125">Nepal</option>,
   <option value="126">Netherlands, The</option>,
   <option value="127">New Caledonia</option>,
   <option value="128">New Zealand</option>,
   <option value="129">Nicaragua</option>,
   <option value="130">Niger</option>,
   <option value="131">Nigeria</option>,
   <option value="132">Northern Mariana Islands</option>,
   <option value="133">Norway</option>,
   <option value="134">Oman</option>,
   <option value="135">Pakistan</option>,
   <option value="136">Palestinian Authority</option>,
   <option value="137">Panama</option>,
   <option value="138">Papua New Guinea</option>,
   <option value="139">Paraguay</option>,
   <option value="140">Peru</option>,
   <option value="141">Philippines</option>,
   <option value="142">Poland</option>,
   <option value="143">Portugal</option>,
   <option value="144">Qatar</option>,
   <option value="145">Republic of Congo</option>,
   <option value="146">Republic of Palau</option>,
   <option value="147">Romania</option>,
   <option value="148">Russia</option>,
   <option value="149">Rwanda</option>,
   <option value="150">Saint Kitts and Nevis</option>,
   <option value="151">Saint Lucia</option>,
   <option value="152">Samoa</option>,
   <option value="153">San Marino</option>,
   <option value="154">Sao Tome and Principe</option>,
   <option value="155">Saudi Arabia</option>,
   <option value="156">Senegal</option>,
   <option value="157">Serbia, Republic Of</option>,
   <option value="158">Seychelles</option>,
   <option value="159">Sierra Leone</option>,
   <option value="160">Singapore</option>,
   <option value="161">Slovakia</option>,
   <option value="162">Slovenia</option>,
   <option value="163">Solomon Islands</option>,
   <option value="164">Somalia</option>,
   <option value="165">South Africa, Republic Of</option>,
   <option value="166">South Sudan</option>,
   <option value="167">Spain</option>,
   <option value="168">Sri Lanka</option>,
   <option value="169">St. Vincent and the Grenadines</option>,
   <option value="170">Stateless</option>,
   <option value="171">Sudan</option>,
   <option value="172">Suriname</option>,
   <option value="173">Swaziland</option>,
   <option value="174">Sweden</option>,
   <option value="175">Switzerland</option>,
   <option value="176">Syria</option>,
   <option value="177">Taiwan</option>,
   <option value="178">Tajikistan</option>,
   <option value="179">Tanzania</option>,
   <option value="180">Thailand</option>,
   <option value="181">Togo</option>,
   <option value="182">Tonga</option>,
   <option value="183">Trinidad and Tobago</option>,
   <option value="184">Tunisia</option>,
   <option value="185">Turkey</option>,
   <option value="186">Turkmenistan</option>,
   <option value="187">Tuvalu</option>,
   <option value="188">Uganda</option>,
   <option value="189">UK - Brit. Ntl. Overseas</option>,
   <option value="190">UK - Brit. overseas citizen</option>,
   <option value="191">UK - Brit. overseas terr.</option>,
   <option value="192">UK - British citizen</option>,
   <option value="193">Ukraine</option>,
   <option value="194">United Arab Emirates</option>,
   <option value="195">United States of America</option>,
   <option value="196">Uruguay</option>,
   <option value="197">Uzbekistan</option>,
   <option value="198">Vanuatu</option>,
   <option value="199">Vatican City State</option>,
   <option value="200">Venezuela</option>,
   <option value="201">Vietnam</option>,
   <option value="202">Western Sahara</option>,
   <option value="203">Yemen</option>,
   <option value="204">Zambia</option>,
   <option value="205">Zimbabwe</option>,
]

export const countryOfCitizenship = [
    <option value="0">AFG (Afghanistan)</option>,
   <option value="1">AGO (Angola)</option>,
   <option value="2">ALB (Albania)</option>,
   <option value="3">AND (Andorra)</option>,
   <option value="4">ANG (Anguilla)</option>,
   <option value="5">ARE (United Arab Emirates)</option>,
   <option value="6">ARG (Argentina)</option>,
   <option value="7">ARM (Armenia)</option>,
   <option value="8">ATG (Antigua And Barbuda)</option>,
   <option value="9">AUS (Australia)</option>,
   <option value="10">AUT (Austria)</option>,
   <option value="11">AZE (Azerbaijan)</option>,
   <option value="12">BDI (Burundi)</option>,
   <option value="13">BEL (Belgium)</option>,
   <option value="14">BEN (Benin)</option>,
   <option value="15">BFA (Burkina Faso)</option>,
   <option value="16">BGD (Bangladesh)</option>,
   <option value="17">BGR (Bulgaria)</option>,
   <option value="18">BHR (Bahrain)</option>,
   <option value="19">BHS (Bahamas)</option>,
   <option value="20">BIH (Bosnia and Herzegovina)</option>,
   <option value="21">BLR (Belarus)</option>,
   <option value="22">BLZ (Belize)</option>,
   <option value="23">BMU (Bermuda)</option>,
   <option value="24">BOL (Bolivia)</option>,
   <option value="25">BRA (Brazil)</option>,
   <option value="26">BRB (Barbados)</option>,
   <option value="27">BRN (Brunei Darussalam)</option>,
   <option value="28">BTN (Bhutan)</option>,
   <option value="29">BWA (Botswana)</option>,
   <option value="30">CAF (Central African Republic)</option>,
   <option value="31">CAN (Canada)</option>,
   <option value="32">CHE (Switzerland)</option>,
   <option value="33">CHL (Chile)</option>,
   <option value="34">CHN (China)</option>,
   <option value="35">CHN (China (Hong Kong SAR))</option>,
   <option value="36">CHN (China (Macao SAR))</option>,
   <option value="37">CIV (Ivory Coast)</option>,
   <option value="38">CMR (Cameroon)</option>,
   <option value="39">COD (Democratic Rep. of Congo)</option>,
   <option value="40">COG (Republic of Congo)</option>,
   <option value="41">COL (Colombia)</option>,
   <option value="42">COM (Comoros)</option>,
   <option value="43">CPV (Cabo Verde)</option>,
   <option value="44">CRI (Costa Rica)</option>,
   <option value="45">CUB (Cuba)</option>,
   <option value="46">CYM (Cayman Islands)</option>,
   <option value="47">CYP (Cyprus)</option>,
   <option value="48">CZE (Czech Republic)</option>,
   <option value="49">D (Germany, Federal Republic Of)</option>,
   <option value="50">DJI (Djibouti)</option>,
   <option value="51">DMA (Dominica)</option>,
   <option value="52">DNK (Denmark)</option>,
   <option value="53">DOM (Dominican Republic)</option>,
   <option value="54">DZA (Algeria)</option>,
   <option value="55">ECU (Ecuador)</option>,
   <option value="56">EGY (Egypt)</option>,
   <option value="57">ERI (Eritrea)</option>,
   <option value="58">ESP (Spain)</option>,
   <option value="59">EST (Estonia)</option>,
   <option value="60">ETH (Ethiopia)</option>,
   <option value="61">FIN (Finland)</option>,
   <option value="62">FJI (Fiji)</option>,
   <option value="63">FRA (France)</option>,
   <option value="64">FSM (Federated States of Micronesia)</option>,
   <option value="65">GAB (Gabon)</option>,
   <option value="66">GBD (UK - Brit. overseas terr.)</option>,
   <option value="67">GBN (UK - Brit. Ntl. Overseas)</option>,
   <option value="68">GBO (UK - Brit. overseas citizen)</option>,
   <option value="69">GBP (UK - Brit. protected person)</option>,
   <option value="70">GBR (UK - British citizen)</option>,
   <option value="71">GBS (UK - British subject)</option>,
   <option value="72">GEO (Georgia)</option>,
   <option value="73">GHA (Ghana)</option>,
   <option value="74">GIN (Guinea)</option>,
   <option value="75">GMB (Gambia)</option>,
   <option value="76">GNB (Guinea-Bissau)</option>,
   <option value="77">GNQ (Equatorial Guinea)</option>,
   <option value="78">GRC (Greece)</option>,
   <option value="79">GRD (Grenada)</option>,
   <option value="80">GTM (Guatemala)</option>,
   <option value="81">GUY (Guyana)</option>,
   <option value="82">HND (Honduras)</option>,
   <option value="83">HRV (Croatia)</option>,
   <option value="84">HTI (Haiti)</option>,
   <option value="85">HUN (Hungary)</option>,
   <option value="86">IDN (Indonesia)</option>,
   <option value="87">IND (India)</option>,
   <option value="88">IRL (Ireland)</option>,
   <option value="89">IRN (Iran)</option>,
   <option value="90">IRQ (Iraq)</option>,
   <option value="91">ISL (Iceland)</option>,
   <option value="92">ISR (Israel)</option>,
   <option value="93">ITA (Italy)</option>,
   <option value="94">JAM (Jamaica)</option>,
   <option value="95">JOR (Jordan)</option>,
   <option value="96">JPN (Japan)</option>,
   <option value="97">KAZ (Kazakhstan)</option>,
   <option value="98">KEN (Kenya)</option>,
   <option value="99">KGZ (Kyrgyzstan)</option>,
   <option value="100">KHM (Cambodia)</option>,
   <option value="101">KIR (Kiribati)</option>,
   <option value="102">KNA (Saint Kitts and Nevis)</option>,
   <option value="103">KOR (Korea, South)</option>,
   <option value="104">KWT (Kuwait)</option>,
   <option value="105">LAO (Laos)</option>,
   <option value="106">LBN (Lebanon)</option>,
   <option value="107">LBR (Liberia)</option>,
   <option value="108">LBY (Libya)</option>,
   <option value="109">LCA (Saint Lucia)</option>,
   <option value="110">LIE (Liechtenstein)</option>,
   <option value="111">LKA (Sri Lanka)</option>,
   <option value="112">LSO (Lesotho)</option>,
   <option value="113">LTU (Lithuania)</option>,
   <option value="114">LUX (Luxembourg)</option>,
   <option value="115">LVA (Latvia)</option>,
   <option value="116">MAR (Morocco)</option>,
   <option value="117">MCO (Monaco)</option>,
   <option value="118">MDA (Moldova)</option>,
   <option value="119">MDG (Madagascar)</option>,
   <option value="120">MDV (Maldives)</option>,
   <option value="121">MEX (Mexico)</option>,
   <option value="122">MHL (Marshall Islands)</option>,
   <option value="123">MKD (Macedonia)</option>,
   <option value="124">MLI (Mali)</option>,
   <option value="125">MLT (Malta)</option>,
   <option value="126">MMR (Burma (Myanmar))</option>,
   <option value="127">MNE (Montenegro)</option>,
   <option value="128">MNG (Mongolia)</option>,
   <option value="129">MOZ (Mozambique)</option>,
   <option value="130">MRT (Mauritania)</option>,
   <option value="131">MSR (Montserrat)</option>,
   <option value="132">MUS (Mauritius)</option>,
   <option value="133">MWI (Malawi)</option>,
   <option value="134">MYS (Malaysia)</option>,
   <option value="135">NAM (Namibia)</option>,
   <option value="136">NER (Niger)</option>,
   <option value="137">NGA (Nigeria)</option>,
   <option value="138">NIC (Nicaragua)</option>,
   <option value="139">NLD (Netherlands, The)</option>,
   <option value="140">NOR (Norway)</option>,
   <option value="141">NPL (Nepal)</option>,
   <option value="142">NRU (Nauru)</option>,
   <option value="143">NZL (New Zealand)</option>,
   <option value="144">OMN (Oman)</option>,
   <option value="145">PAK (Pakistan)</option>,
   <option value="146">PAN (Panama)</option>,
   <option value="147">PER (Peru)</option>,
   <option value="148">PHL (Philippines)</option>,
   <option value="149">PLW (Republic of Palau)</option>,
   <option value="150">PNG (Papua New Guinea)</option>,
   <option value="151">POL (Poland)</option>,
   <option value="152">PRK (Korea, North (DPRK))</option>,
   <option value="153">PRT (Portugal)</option>,
   <option value="154">PRY (Paraguay)</option>,
   <option value="155">PSE (Palestinian Authority)</option>,
   <option value="156">QAT (Qatar)</option>,
   <option value="157">RKS (Kosovo)</option>,
   <option value="158">ROU (Romania)</option>,
   <option value="159">RUS (Russia)</option>,
   <option value="160">RWA (Rwanda)</option>,
   <option value="161">SAU (Saudi Arabia)</option>,
   <option value="162">SDN (Sudan)</option>,
   <option value="163">SEN (Senegal)</option>,
   <option value="164">SGP (Singapore)</option>,
   <option value="165">SHN (Saint Helena)</option>,
   <option value="166">SLB (Solomon Islands)</option>,
   <option value="167">SLE (Sierra Leone)</option>,
   <option value="168">SLV (El Salvador)</option>,
   <option value="169">SMR (San Marino)</option>,
   <option value="170">SOM (Somalia)</option>,
   <option value="171">SRB (Serbia, Republic Of)</option>,
   <option value="172">SSD (South Sudan)</option>,
   <option value="173">STP (Sao Tome and Principe)</option>,
   <option value="174">SUR (Suriname)</option>,
   <option value="175">SVK (Slovakia)</option>,
   <option value="176">SVN (Slovenia)</option>,
   <option value="177">SWE (Sweden)</option>,
   <option value="178">SWZ (Swaziland)</option>,
   <option value="179">SYC (Seychelles)</option>,
   <option value="180">SYR (Syria)</option>,
   <option value="181">TCA (Turks and Caicos Islands)</option>,
   <option value="182">TCD (Chad)</option>,
   <option value="183">TGO (Togo)</option>,
   <option value="184">THA (Thailand)</option>,
   <option value="185">TJK (Tajikistan)</option>,
   <option value="186">TKM (Turkmenistan)</option>,
   <option value="187">TLS (East Timor)</option>,
   <option value="188">TON (Tonga)</option>,
   <option value="189">TTO (Trinidad and Tobago)</option>,
   <option value="190">TUN (Tunisia)</option>,
   <option value="191">TUR (Turkey)</option>,
   <option value="192">TUV (Tuvalu)</option>,
   <option value="193">TWN (Taiwan)</option>,
   <option value="194">TZA (Tanzania)</option>,
   <option value="195">UGA (Uganda)</option>,
   <option value="196">UKR (Ukraine)</option>,
   <option value="197">UNA (UN specialized agency)</option>,
   <option value="198">UNO (UN or official)</option>,
   <option value="199">URY (Uruguay)</option>,
   <option value="200">USA (United States of America)</option>,
   <option value="201">UZB (Uzbekistan)</option>,
   <option value="202">VAT (Vatican City State)</option>,
   <option value="203">VCT (St. Vincent and the Grenadines)</option>,
   <option value="204">VEN (Venezuela)</option>,
   <option value="205">VGB (British Virgin Islands)</option>,
   <option value="206">VNM (Vietnam)</option>,
   <option value="207">VUT (Vanuatu)</option>,
   <option value="208">WSM (Samoa)</option>,
   <option value="209">YEM (Yemen)</option>,
   <option value="210">ZAF (South Africa, Republic Of)</option>,
   <option value="211">ZMB (Zambia)</option>,
   <option value="212">ZWE (Zimbabwe)</option>,
]

export const new_kdmid_accommodation_type_list = {
    en: [
        <option value="0">Hotel</option>,
        <option value="1">Individual</option>
    ],
    fr: [
        <option value="0">Hôtel</option>,
        <option value="1">Individuel</option>
    ],
    es: [
        <option value="0">Hotel</option>,
        <option value="1">Individual</option>
    ],
    de: [
        <option value="0">Hotel</option>,
        <option value="1">Individuell</option>
    ],
    it: [
        <option value="0">Hotel</option>,
        <option value="1">Individuale</option>
    ],
}

export const new_kdmid_passport_type_list = {
    en: [
        <option value="1">Passport</option>,
        <option value="2">Service passport</option>,
        <option value="3">Diplomatic passport</option>
    ],
    fr: [
        <option value="1">Passeport</option>,
        <option value="2">Passeport de service</option>,
        <option value="3">Passeport diplomatique</option>
    ],
    es: [
        <option value="1">Pasaporte</option>,
        <option value="2">Pasaporte de servicio</option>,
        <option value="3">Pasaporte diplomático</option>
    ],
    de: [
        <option value="14">Reisepass</option>,
        <option value="2">Servicepass</option>,
        <option value="3">Diplomatenpass</option>
    ],
    it: [
        <option value="1">Passaporto</option>,
        <option value="2">Passaporto di servizio</option>,
        <option value="3">Passaporto diplomatico</option>
    ],
}


export const new_kdmid_relation_degree_list = {
    en: [
        <option value="1">HUSBAND</option>,
        <option value="2">WIFE</option>,
        <option value="3">FATHER</option>,
        <option value="4">MOTHER</option>,
        <option value="5">SON</option>,
        <option value="6">DAUGHTER</option>,
        <option value="7">GRAND-FATHER</option>,
        <option value="8">GRAND-MOTHER</option>,
        <option value="9">GRAND-SON</option>,
        <option value="10">GRAND-DAUGHTER</option>,
        <option value="20">BROTHER</option>,
        <option value="21">SISTER</option>,
        <option value="40">STEP-FATHER</option>,
        <option value="41">STEP-MOTHER</option>,
        <option value="42">STEP-SON</option>,
        <option value="43">STEP-DAUGHTER</option>,
        <option value="50">FATHER-IN-LAW</option>,
        <option value="51">MOTHER-IN-LAW</option>,
        <option value="54">SON-IN-LAW</option>,
        <option value="56">DAUGHTER-IN-LAW</option>,
        <option value="60">GREAT-GRAND-FATHER</option>,
        <option value="61">GREAT-GRAND-MOTHER</option>,
        <option value="62">GREAT-GRAND-SON</option>,
        <option value="63">GREAT-GRAND-DAUGHTER</option>,
        <option value="71">UNCLE</option>,
        <option value="72">AUNT</option>,
        <option value="73">NEPHEW</option>,
        <option value="74">NIECE</option>,
        <option value="170">OTHER KINSHIP</option>
    ],
    fr: [
        <option value="1">Mari</option>,
        <option value="2">ÉPOUSE</option>,
        <option value="3">PÈRE</option>,
        <option value="4">MÈRE</option>,
        <option value="5">FILS</option>,
        <option value="6">FILLE</option>,
        <option value="7">GRAND-PÈRE</option>,
        <option value="8">GRAND-MÈRE</option>,
        <option value="9">PETIT FILS</option>,
        <option value="10">PETITE FILLE</option>,
        <option value="20">FRÈRE</option>,
        <option value="21">SŒUR</option>,
        <option value="40">BEAU-PÈRE(PAR AFFILIATION)</option>,
        <option value="41">BELLE-MÈRE(PAR AFFILIATION)</option>,
        <option value="42">BEAU-FILS(PAR AFFILIATION)</option>,
        <option value="43">BELLE-FILLE(PAR AFFILIATION)</option>,
        <option value="50">BEAU-PÈRE(PAR MARIAGE)</option>,
        <option value="51">BELLE-MÈRE(PAR MARIAGE)</option>,
        <option value="54">GENDRE(PAR MARIAGE)</option>,
        <option value="56">BELLE-FILLE(PAR MARIAGE)</option>,
        <option value="60">ARRIÈRE GRAND PÈRE</option>,
        <option value="61">ARRIÈRE GRAND-MÈRE</option>,
        <option value="62">ARRIÈRE-PETIT-FILS</option>,
        <option value="63">ARRIÈRE PETITE FILLE</option>,
        <option value="71">ONCLE</option>,
        <option value="72">TANTE</option>,
        <option value="73">NEVEU</option>,
        <option value="74">NIÈCE</option>,
        <option value="170">AUTRE</option>
    ],
    es: [
        <option value="1">MARIDO</option>,
        <option value="2">ESPOSA</option>,
        <option value="3">PADRE</option>,
        <option value="4">MADRE</option>,
        <option value="5">HIJO</option>,
        <option value="6">HIJA</option>,
        <option value="7">ABUELO</option>,
        <option value="8">ABUELA</option>,
        <option value="9">NIETO</option>,
        <option value="10">NIETA</option>,
        <option value="20">HERMANO</option>,
        <option value="21">HERMANA</option>,
        <option value="40">PADRASTRO</option>,
        <option value="41">MADRASTRA</option>,
        <option value="42">HIJASTRO</option>,
        <option value="43">HIJASTRA</option>,
        <option value="50">SUEGRO</option>,
        <option value="51">SUEGRA</option>,
        <option value="54">YERNO</option>,
        <option value="56">HIJASTRA</option>,
        <option value="60">BISABUELO</option>,
        <option value="61">BISABUELA</option>,
        <option value="62">BISNIETO</option>,
        <option value="63">BISNIETA</option>,
        <option value="71">TÍO</option>,
        <option value="72">TÍA</option>,
        <option value="73">SOBRINO</option>,
        <option value="74">NIECE</option>,
        <option value="170">OTRO</option>
    ],
    de: [
        <option value="1">MANN</option>,
        <option value="2">EHEFRAU</option>,
        <option value="3">VATER</option>,
        <option value="4">MUTTER</option>,
        <option value="5">SOHN</option>,
        <option value="6">TOCHTER</option>,
        <option value="7">GROSSVATER</option>,
        <option value="8">OMA</option>,
        <option value="9">ENKEL</option>,
        <option value="10">ENKELINR</option>,
        <option value="20">BRUDER</option>,
        <option value="21">SCHWESTER</option>,
        <option value="40">STIEFVATER</option>,
        <option value="41">STIEFMUTTER</option>,
        <option value="42">STIEFSOHN</option>,
        <option value="43">STIEFTOCHTER</option>,
        <option value="50">SCHWIEGERVATER</option>,
        <option value="51">SCHWIEGERMUTTER</option>,
        <option value="54">SCHWIEGERSOHN</option>,
        <option value="56">SCHWIEGERTOCHTER</option>,
        <option value="60">URGROSSVATER</option>,
        <option value="61">UROMA</option>,
        <option value="62">URENKEL</option>,
        <option value="63">URENKELIN</option>,
        <option value="71">ONKEL</option>,
        <option value="72">TANTE</option>,
        <option value="73">NEFFE</option>,
        <option value="74">NICHTE</option>,
        <option value="170">ANDERE</option>
    ],
    it: [
        <option value="1">MARITO</option>,
        <option value="2">MOGLIE</option>,
        <option value="3">PADRE</option>,
        <option value="4">MMADRE</option>,
        <option value="5">FIGLIO</option>,
        <option value="6">FIGLIA</option>,
        <option value="7">NONNO</option>,
        <option value="8">NONNA</option>,
        <option value="9">NIPOTE</option>,
        <option value="10">NIPOTINA</option>,
        <option value="20">FRATELLO</option>,
        <option value="21">SORELLA</option>,
        <option value="40">PATRIGNO</option>,
        <option value="41">MATRIGNAR</option>,
        <option value="42">FIGLIASTRO</option>,
        <option value="43">FIGLIASTRA</option>,
        <option value="50">SUOCERO</option>,
        <option value="51">SUOCERA</option>,
        <option value="54">GENERO</option>,
        <option value="56">NUORA</option>,
        <option value="60">BISNONNO</option>,
        <option value="61">BISNONNA</option>,
        <option value="62">PRONIPOTE(Maschio)</option>,
        <option value="63">PRONIPOTE(Femmina)</option>,
        <option value="71">ZIO</option>,
        <option value="72">ZIA</option>,
        <option value="73">NIPOTE(Maschio)</option>,
        <option value="74">NIPOTE(Femmina)</option>,
        <option value="170">ALTRO</option>
    ],
}
/* Dropdown Translation End */

export const countries_only_option_label_list = [
    "AFGHANISTAN",
    "ALBANIA",
    "ALGERIA",
    "ANDORRA",
    "ANGOLA",
    "ANGUILLA",
    "ANTIGUA AND BARBUDA",
    "ARGENTINA",
    "ARMENIA",
    "AUSTRALIA",
    "AUSTRIA",
    "AZERBAIJAN",
    "BAHAMAS",
    "BAHRAIN",
    "BANGLADESH",
    "BARBADOS",
    "BELARUS",
    "BELGIUM",
    "BELIZE",
    "BENIN",
    "BERMUDA",
    "BHUTAN",
    "BOLIVIA",
    "BOSNIA-HERZEGOVINA",
    "BOTSWANA",
    "BRAZIL",
    "BRITISH INDIAN OCEAN TERRITORY",
    "BRUNEI",
    "BULGARIA",
    "BURKINA FASO",
    "BURMA",
    "BURUNDI",
    "CAMBODIA",
    "CAMEROON",
    "CANADA",
    "CABO VERDE",
    "CAYMAN ISLANDS",
    "CENTRAL AFRICAN REPUBLIC",
    "CHAD",
    "CHILE",
    "CHINA",
    "COLOMBIA",
    "COMOROS",
    "CONGO, DEMOCRATIC REPUBLIC OF THE",
    "CONGO, REPUBLIC OF THE",
    "COSTA RICA",
    "COTE D`IVOIRE",
    "CROATIA",
    "CUBA",
    "CYPRUS",
    "CZECH REPUBLIC",
    "DENMARK",
    "DJIBOUTI",
    "DOMINICA",
    "DOMINICAN REPUBLIC",
    "ECUADOR",
    "EGYPT",
    "EL SALVADOR",
    "EQUATORIAL GUINEA",
    "ERITREA",
    "ESTONIA",
    "ESWATINI",
    "ETHIOPIA",
    "FIJI",
    "FINLAND",
    "FRANCE",
    "GABON",
    "GAMBIA, THE",
    "GEORGIA",
    "GERMANY",
    "GHANA",
    "GIBRALTAR",
    "GREECE",
    "GRENADA",
    "GUATEMALA",
    "GUINEA",
    "GUINEA - BISSAU",
    "GUYANA",
    "HAITI",
    "HOLY SEE (VATICAN CITY)",
    "HONDURAS",
    "HONG KONG BNO",
    "HONG KONG SAR",
    "HUNGARY",
    "ICELAND",
    "INDIA",
    "INDONESIA",
    "IRAN",
    "IRAQ",
    "IRELAND",
    "ISRAEL",
    "ITALY",
    "JAMAICA",
    "JAPAN",
    "JORDAN",
    "KAZAKHSTAN",
    "KENYA",
    "KIRIBATI",
    "KOREA, DEMOCRATIC REPUBLIC OF (NORTH)",
    "KOREA, REPUBLIC OF (SOUTH)",
    "KOSOVO",
    "KUWAIT",
    "KYRGYZSTAN",
    "LAOS",
    "LATVIA",
    "LEBANON",
    "LESOTHO",
    "LIBERIA",
    "LIBYA",
    "LIECHTENSTEIN",
    "LITHUANIA",
    "LUXEMBOURG",
    "MACAU",
    "MACEDONIA",
    "MADAGASCAR",
    "MALAWI",
    "MALAYSIA",
    "MALDIVES",
    "MALI",
    "MALTA",
    "MARSHALL ISLANDS",
    "MAURITANIA",
    "MAURITIUS",
    "MEXICO",
    "MICRONESIA",
    "MOLDOVA",
    "MONACO",
    "MONGOLIA",
    "MONTENEGRO",
    "MONTSERRAT",
    "MOROCCO",
    "MOZAMBIQUE",
    "NAMIBIA",
    "NAURU",
    "NEPAL",
    "NETHERLANDS",
    "NEW ZEALAND",
    "NICARAGUA",
    "NIGER",
    "NIGERIA",
    "NORWAY",
    "OMAN",
    "PAKISTAN",
    "PALAU",
    "PALESTINIAN AUTHORITY",
    "PANAMA",
    "PAPUA NEW GUINEA",
    "PARAGUAY",
    "PERU",
    "PHILIPPINES",
    "PITCAIRN ISLANDS",
    "POLAND",
    "PORTUGAL",
    "QATAR",
    "ROMANIA",
    "RUSSIA",
    "RWANDA",
    "SAMOA",
    "SAN MARINO",
    "SAO TOME AND PRINCIPE",
    "SAUDI ARABIA",
    "SENEGAL",
    "SERBIA",
    "SEYCHELLES",
    "SIERRA LEONE",
    "SINGAPORE",
    "SLOVAKIA",
    "SLOVENIA",
    "SOLOMON ISLANDS",
    "SOMALIA",
    "SOUTH AFRICA",
    "SOUTH SUDAN",
    "SPAIN",
    "SRI LANKA",
    "ST. HELENA",
    "ST. KITTS AND NEVIS",
    "ST. LUCIA",
    "ST. VINCENT AND THE GRENADINES",
    "STATELESS",
    "SUDAN",
    "SURINAME",
    "SWEDEN",
    "SWITZERLAND",
    "SYRIA",
    "TAIWAN",
    "TAJIKISTAN",
    "TANZANIA",
    "THAILAND",
    "TIMOR-LESTE",
    "TOGO",
    "TONGA",
    "TRINIDAD AND TOBAGO",
    "TUNISIA",
    "TURKEY",
    "TURKMENISTAN",
    "TURKS AND CAICOS ISLANDS",
    "TUVALU",
    "UGANDA",
    "UKRAINE",
    "UNITED ARAB EMIRATES",
    "UNITED KINGDOM",
    "UNITED STATES OF AMERICA",
    "URUGUAY",
    "UZBEKISTAN",
    "VANUATU",
    "VENEZUELA",
    "VIETNAM",
    "VIRGIN ISLANDS, BRITISH",
    "WALLIS AND FUTUNA ISLANDS",
    "WESTERN SAHARA",
    "YEMEN",
    "ZAMBIA",
    "ZIMBABWE",
];

export const countries_only_option_value_list = [
    "AFGH",
    "ALB",
    "ALGR",
    "ANDO",
    "ANGL",
    "ANGU",
    "ANTI",
    "ARG",
    "ARM",
    "ASTL",
    "AUST",
    "AZR",
    "BAMA",
    "BAHR",
    "BANG",
    "BRDO",
    "BYS",
    "BELG",
    "BLZ",
    "BENN",
    "BERM",
    "BHU",
    "BOL",
    "BIH",
    "BOT",
    "BRZL",
    "IOT",
    "BRNI",
    "BULG",
    "BURK",
    "BURM",
    "BRND",
    "CBDA",
    "CMRN",
    "CAN",
    "CAVI",
    "CAYI",
    "CAFR",
    "CHAD",
    "CHIL",
    "CHIN",
    "COL",
    "COMO",
    "COD",
    "CONB",
    "CSTR",
    "IVCO",
    "HRV",
    "CUBA",
    "CYPR",
    "CZEC",
    "DEN",
    "DJI",
    "DOMN",
    "DOMR",
    "ECUA",
    "EGYP",
    "ELSL",
    "EGN",
    "ERI",
    "EST",
    "SZLD",
    "ETH",
    "FIJI",
    "FIN",
    "FRAN",
    "GABN",
    "GAM",
    "GEO",
    "GER",
    "GHAN",
    "GIB",
    "GRC",
    "GREN",
    "GUAT",
    "GNEA",
    "GUIB",
    "GUY",
    "HAT",
    "VAT",
    "HOND",
    "HOKO",
    "HNK",
    "HUNG",
    "ICLD",
    "IND",
    "IDSA",
    "IRAN",
    "IRAQ",
    "IRE",
    "ISRL",
    "ITLY",
    "JAM",
    "JPN",
    "JORD",
    "KAZ",
    "KENY",
    "KIRI",
    "PRK",
    "KOR",
    "KSV",
    "KUWT",
    "KGZ",
    "LAOS",
    "LATV",
    "LEBN",
    "LES",
    "LIBR",
    "LBYA",
    "LCHT",
    "LITH",
    "LXM",
    "MAC",
    "MKD",
    "MADG",
    "MALW",
    "MLAS",
    "MLDV",
    "MALI",
    "MLTA",
    "RMI",
    "MAUR",
    "MRTS",
    "MEX",
    "FSM",
    "MLD",
    "MON",
    "MONG",
    "MTG",
    "MONT",
    "MORO",
    "MOZ",
    "NAMB",
    "NAU",
    "NEP",
    "NETH",
    "NZLD",
    "NIC",
    "NIR",
    "NRA",
    "NORW",
    "OMAN",
    "PKST",
    "PALA",
    "PAL",
    "PAN",
    "PNG",
    "PARA",
    "PERU",
    "PHIL",
    "PITC",
    "POL",
    "PORT",
    "QTAR",
    "ROM",
    "RUS",
    "RWND",
    "WSAM",
    "SMAR",
    "STPR",
    "SARB",
    "SENG",
    "SBA",
    "SEYC",
    "SLEO",
    "SING",
    "SVK",
    "SVN",
    "SLMN",
    "SOMA",
    "SAFR",
    "SSDN",
    "SPN",
    "SRL",
    "SHEL",
    "STCN",
    "SLCA",
    "STVN",
    "XXX",
    "SUDA",
    "SURM",
    "SWDN",
    "SWTZ",
    "SYR",
    "TWAN",
    "TJK",
    "TAZN",
    "THAI",
    "TMOR",
    "TOGO",
    "TONG",
    "TRIN",
    "TNSA",
    "TRKY",
    "TKM",
    "TCIS",
    "TUV",
    "UGAN",
    "UKR",
    "UAE",
    "GRBR",
    "USA",
    "URU",
    "UZB",
    "VANU",
    "VENZ",
    "VTNM",
    "BRVI",
    "WAFT",
    "SSAH",
    "YEM",
    "ZAMB",
    "ZIMB",
]

export const state_options = [
    <option value="AL">ALABAMA</option>,
    <option value="AK">ALASKA</option>,
    <option value="AS">AMERICAN SAMOA</option>,
    <option value="AZ">ARIZONA</option>,
    <option value="AR">ARKANSAS</option>,
    <option value="CA">CALIFORNIA</option>,
    <option value="CO">COLORADO</option>,
    <option value="CT">CONNECTICUT</option>,
    <option value="DE">DELAWARE</option>,
    <option value="DC">DISTRICT OF COLUMBIA</option>,
    <option value="FL">FLORIDA</option>,
    <option value="GA">GEORGIA</option>,
    <option value="GU">GUAM</option>,
    <option value="HI">HAWAII</option>,
    <option value="ID">IDAHO</option>,
    <option value="IL">ILLINOIS</option>,
    <option value="IN">INDIANA</option>,
    <option value="IA">IOWA</option>,
    <option value="KS">KANSAS</option>,
    <option value="KY">KENTUCKY</option>,
    <option value="LA">LOUISIANA</option>,
    <option value="ME">MAINE</option>,
    <option value="MD">MARYLAND</option>,
    <option value="MA">MASSACHUSETTS</option>,
    <option value="MI">MICHIGAN</option>,
    <option value="MN">MINNESOTA</option>,
    <option value="MS">MISSISSIPPI</option>,
    <option value="MO">MISSOURI</option>,
    <option value="MT">MONTANA</option>,
    <option value="NE">NEBRASKA</option>,
    <option value="NV">NEVADA</option>,
    <option value="NH">NEW HAMPSHIRE</option>,
    <option value="NJ">NEW JERSEY</option>,
    <option value="NM">NEW MEXICO</option>,
    <option value="NY">NEW YORK</option>,
    <option value="NC">NORTH CAROLINA</option>,
    <option value="ND">NORTH DAKOTA</option>,
    <option value="MP">NORTHERN MARIANA ISLANDS</option>,
    <option value="OH">OHIO</option>,
    <option value="OK">OKLAHOMA</option>,
    <option value="OR">OREGON</option>,
    <option value="PA">PENNSYLVANIA</option>,
    <option value="PR">PUERTO RICO</option>,
    <option value="RI">RHODE ISLAND</option>,
    <option value="SC">SOUTH CAROLINA</option>,
    <option value="SD">SOUTH DAKOTA</option>,
    <option value="TN">TENNESSEE</option>,
    <option value="TX">TEXAS</option>,
    <option value="UT">UTAH</option>,
    <option value="VT">VERMONT</option>,
    <option value="VI">VIRGIN ISLANDS</option>,
    <option value="VA">VIRGINIA</option>,
    <option value="WA">WASHINGTON</option>,
    <option value="WV">WEST VIRGINIA</option>,
    <option value="WI">WISCONSIN</option>,
    <option value="WY">WYOMING</option>,
]

export const new_kdmid_hints_and_help_language = [
    <option value="en-US">ENGLISH</option>,
    <option value="fr-FR">FRANÇAIS (FRENCH)</option>,
    <option value="es-ES">ESPAÑOL (SPANISH)</option>,
    <option value="de-DE">DEUTSCH (GERMAN)</option>,
    <option value="it-IT">ITALIANO (ITALIAN)</option>
]
