export const translate = (r, lang) => {
    if(!lang) 
        return r.en ? r.en : ''
    const pre = lang.split('-')[0]; 
    return r[pre] ? r[pre] : (r.en ? r.en : '') 
}
const resources = {
    before: {
        section_title: {
            en: `Make sure you enter your passport information correctly`,
            fr: `Assurez-vous d'entrer correctement les informations de votre passeport`,
            it: `Assicurati di inserire il tuo passaporto informazioni correttamente`,
            de: `Stellen Sie sicher, dass Sie geben Sie Ihre passport-Informationen korrekt`,
            es: `Asegúrate de introducir la información del pasaporte correctamente`,
        },
        disclaimer_1: {
            en: `DISCLAIMER: Before you begin this application, make sure that you have a valid passport and credit card available. This application will only accept the following credit cards: MasterCard, VISA, American Express, and Discover (JCB, Diners Club).`,
            fr: `AVERTISSEMENT: Avant de commencer cette demande, assurez-vous que vous avez un passeport valide et une carte de crédit disponible. Cette application accepte uniquement les cartes de crédit suivantes: MasterCard, VISA, American Express et Discover (JCB, Diners Club).`,
            it: `ESCLUSIONE DI RESPONSABILITÀ: prima di iniziare questa applicazione, assicurarsi di disporre di un passaporto e di una carta di credito validi. Questa applicazione accetta solo le seguenti carte di credito: MasterCard, VISA, American Express e Discover (JCB, Diners Club).`,
            de: `HAFTUNGSAUSSCHLUSS: Bevor Sie mit dieser Anwendung beginnen, stellen Sie sicher, dass Sie über einen gültigen Reisepass und eine gültige Kreditkarte verfügen. Diese Anwendung akzeptiert nur die folgenden Kreditkarten: MasterCard, VISA, American Express und Discover (JCB, Diners Club).`,
            es: `DESCARGO DE RESPONSABILIDAD: Antes de comenzar esta solicitud, asegúrese de tener un pasaporte válido y una tarjeta de crédito disponibles. Esta aplicación solo aceptará las siguientes tarjetas de crédito: MasterCard, VISA, American Express y Discover (JCB, Diners Club).`,
        },
        disclaimer_2: {
            en: `All information provided by you, or on your behalf by a designated third party, must be true and correct. This application costs $79 and is not refundable except if your eTA is denied. You many be subject to administrative or criminal penalties if you knowingly and willfully make a materially false, fictitious, or fraudulent statement or representation in an electronic travel authorization application submitted by you or on your behalf.`,
            fr: `Toutes les informations fournies par vous ou en votre nom par un tiers désigné doivent être véridiques et correctes. Cette demande coûte 79 $ et n'est pas remboursable sauf si votre AVE est refusée. Vous pourriez être passible de sanctions administratives ou pénales si vous faites sciemment et volontairement une déclaration ou une représentation matériellement fausse, fictive ou frauduleuse dans une demande d'autorisation de voyage électronique soumise par vous ou en votre nom.`,
            it: `Tutte le informazioni fornite da te o per tuo conto da una terza parte designata devono essere vere e corrette. Questa applicazione costa $ 79 e non è rimborsabile, tranne se il tuo eTA viene negato. Molti sono soggetti a sanzioni amministrative o penali se si fa consapevolmente e intenzionalmente una dichiarazione o una rappresentazione materialmente falsa, fittizia o fraudolenta in una domanda di autorizzazione di viaggio elettronica inviata dall'utente o per suo conto.`,
            de: `Alle von Ihnen oder in Ihrem Namen von einem bestimmten Dritten bereitgestellten Informationen müssen wahr und richtig sein. Dieser Antrag kostet 79 US-Dollar und kann nur zurückerstattet werden, wenn Ihre eTA abgelehnt wird. Sie können verwaltungs- oder strafrechtlich verfolgt werden, wenn Sie in einem von Ihnen oder in Ihrem Namen eingereichten Antrag auf elektronische Reisegenehmigung wissentlich und vorsätzlich eine sachlich falsche, fiktive oder betrügerische Erklärung oder Darstellung abgeben.`,
            es: `Toda la información proporcionada por usted, o en su nombre por un tercero designado, debe ser verdadera y correcta. Esta aplicación cuesta $ 79 y no es reembolsable, excepto si se niega su eTA. Usted puede estar sujeto a sanciones administrativas o penales si realiza una declaración o representación materialmente falsa, ficticia o fraudulenta en una solicitud de autorización electrónica de viaje presentada por usted o en su nombre.`,
        },
        disclaimer_3: {
            en: 'Entering incorrect information could lead to a delay or even a refusal of an eTA application and/or prevent the applicant from boarding their flight.',
            fr: `La saisie d'informations incorrectes peut entraîner un retard, voire un refus d'une demande d'AVE et / ou empêcher le demandeur d'embarquer sur son vol.`,
            it: `L'immissione di informazioni errate può comportare un ritardo o addirittura il rifiuto di una domanda di eTA e / o impedire al richiedente di salire a bordo del proprio volo.`,
            de: `Die Eingabe falscher Informationen kann zu einer Verzögerung oder sogar Ablehnung eines eTA-Antrags führen und / oder den Antragsteller daran hindern, seinen Flug zu betreten.`,
            es: `Ingresar información incorrecta podría ocasionar una demora o incluso el rechazo de una solicitud de eTA y / o evitar que el solicitante aborde su vuelo.`
        },
        bPassportFranceOrVenezuela: {
            en: `Do you have a passport issued by France or Venezuela? `,
            fr: `Avez-vous un passeport délivré par la France ou le Venezuela? `,
            it: `Avete un passaporto rilasciato da Francia o in Venezuela? `,
            de: `Haben Sie einen Reisepass, ausgestellt von Frankreich oder Venezuela? `,
            es: `¿Usted tiene un pasaporte expedido por Francia o Venezuela? `,
        },
        bFrance: {
            en: `Which country issued your passport? `,
            fr: `Le pays qui vous a délivré votre passeport? `,
            it: `Che paese che ha rilasciato il passaporto? `,
            de: `Welches Land ausgestellten Pass? `,
            es: `País que expidió el pasaporte? `,
        },
        bHasGreenCard: {
            en: `Are you a lawful permanent resident of the U.S. and have an alien registration card (Green Card)? `,
            fr: `Êtes-vous un résident permanent légal des états-UNIS et avoir une inscription au registre des étrangers (carte Verte)? `,
            it: `Sei un residente permanente degli stati UNITI e hanno un alien registration card (Carta Verde)? `,
            de: `Sind Sie ein rechtmäßigen ständigen Wohnsitz in den USA und haben eine alien registration card (Green Card)? `,
            es: `¿Es usted un residente permanente legal de los estados UNIDOS y tiene una tarjeta de residencia (Green Card)? `,
        },
        bVenezuelaPassportExpired: {
            en: `Has the printed expiry date on your Venezuelan passport already passed? `,
            fr: `A la date d'expiration imprimée sur votre passeport Vénézuélien déjà passé? `,
            it: `Ha stampata la data di scadenza sul vostro Bolivar passaporto già passato? `,
            de: `Hat das gedruckte Ablaufdatum auf dem Venezolanischen Pass bereits abgelaufen ist? `,
            es: `Tiene impresa la fecha de caducidad de su pasaporte Venezolano ya ha pasado? `,
        },
        bUCI: {
            label: {
                en: `Has the printed expiry date on your Venezuelan passport already passed? `,
                fr: `A la date d'expiration imprimée sur votre passeport Vénézuélien déjà passé? `,
                it: `Ha stampata la data di scadenza sul vostro Bolivar passaporto già passato? `,
                de: `Hat das gedruckte Ablaufdatum auf dem Venezolanischen Pass bereits abgelaufen ist? `,
                es: `Tiene impresa la fecha de caducidad de su pasaporte Venezolano ya ha pasado? `,
            },
            extra: {
                en: `This is an 8 or 10-digit number. You have this number if you applied to IRCC in the past. You can find it on an approval or refusal letter from IRCC.`,
                fr: `C'est un 8 ou 10 chiffres. Vous avez ce numéro si vous avez appliqué pour CRIC dans le passé. Vous pouvez le trouver sur l'approbation ou le refus de la lettre de l'IRCC.`,
                it: `Questo è un 8 o un numero di 10 cifre. Si dispone di questo numero, se applicato all'IRCC in passato. Puoi trovare l'approvazione o la lettera di rifiuto da IRCC.`,
                de: `Dies ist ein 8-oder 10-stellige Nummer. Sie haben diese Nummer, wenn Sie angewendet IRCC in der Vergangenheit. Sie finden es auf eine Zulassung oder die Verweigerung der Brief vom IRCC.`,
                es: `Este es un 8 o 10 dígitos. Usted tiene este número, si se aplica a IRCC en el pasado. Usted puede encontrar en una aprobación o denegación de la carta de IRCC.`,
            },
        },
        start_button: {
            en: `Start Your Application`,
            fr: `Compléter un nouveau formulaire`,
            es: `Rellenar nuevo cuestionario`,
            de: `Neuen Antragsformular ausfüllen`,
            it: `Compila un nuovo modulo`,
        },
    },
    validations: {
        required: {
            en: `This field is required`,
            fr: `Ce champ de saisie est obligatoire`,
            es: `Campo obligatorio para rellenar`,
            de: `Das ist ein Pflichtfeld.`,
            it: `E obbligatorio compilare questo campo`,
        },
        validateEmailConfirm: {
            notmatch: {
                en: `The confirmation e-mail must match your e-mail address.`,
                fr: `L'e-mail de confirmation doit correspondre à votre adresse e-mail.`,
                es: `El e-mail de confirmación debe coincidir con su dirección de correo electrónico.`,
                de: `Die Bestätigungs-e-mail müssen mit Ihrem e-mail-Adresse.`,
                it: `L'e-mail di conferma deve corrispondere il vostro indirizzo di posta elettronica.`,
            },
        },
    },
    yes: {
        en: `Yes`,
        fr: `Oui`,
        it: `Sì`,
        es: `Sí`,
        de: `Ja`,
    },
    no: {
        en: `No`,
        fr: `Non`,
        it: `No`,
        es: `No`,
        de: `No`,
    },
    add_another: {
        en: `Add another`,
        fr: `Ajouter un autre`,
        it: `Agrega otro`,
        es: `Neue hinzufügen`,
        de: `Aggiungi un altro`,
    },
    prev: {
        en: 'Prev',
        fr: 'Prec',
        es: 'Antes',
        de: 'Bis',
        it: 'Prec',
    },
    next: {
        en: 'Next',
        fr: 'Suiv',
        es: 'Próximo',
        de: 'Folgende',
        it: 'Seguente',
    },
    save_and_continue_later: {
        en: 'Save an Continue Later',
        fr: 'Enregistrer un continuer plus tard',
        es: 'Guardar y continuar más tarde',
        de: 'Speichern und später fortsetzen',
        it: 'Salva e continua più tardi',
    },
    submit_with_payment: {
        en: 'SUBMIT AND MAKE YOUR PAYMENT',
        fr: 'SOUMETTRE ET EFFECTUER VOTRE PAIEMENT',
        es: 'ENVÍE Y HAGA SU PAGO',
        de: 'Übermitteln Sie und machen Sie Ihre Zahlung',
        it: 'INVIA E EFFETTUA IL TUO PAGAMENTO',
    },
    language: {
        label: {
            en: `Hints and help language`,
            fr: `Astuces et langage d'aide`,
            de: `Tipps und Hilfe-Sprache`,
            it: `Aiuto e suggerimenti lingua`,
            es: `Consejos y ayuda de idioma`,
        },
        extra: {
            en: `Select language in which you would like the hints, regarding completion of the application form, to be displayed`,
            fr: `Indiquez la langue des conseils sur le remplissage de votre demande de visa`,
            es: `Indique el idioma de soplos de la lista “Hints and help language”.`,
            de: `Geben Sie bitte die Sprache der Ausfüllhilfen an.`,
            it: `Indicare la lingua delle spiegazioni`,
        },
    },
    submit_your_application: {
        en: `Submit your application`,
        fr: `Soumettez votre candidature`,
        es: `Envía tu solicitud`,
        de: `Reichen Sie Ihre Bewerbung ein`,
        it: `Invia la tua domanda`,
    },
    continue_to_appointment: {
        en: 'Continue to Your Appointment Information',
        fr: 'Continuez vers vos informations de rendez-vous',
        es: 'Continúe con la información de su cita',
        de: 'Fahren Sie mit Ihren Termininformationen fort',
        it: `Continua con le informazioni sull'appuntamento`,
    },
    step_welcome: {
        section_title: {
            en: `DISCLAIMER: On this website you can fill out the Application for an Electronic Travel Authorization (eTA) form and print the eTA application form, required for applying for a visa to the Canada. EACH TRAVELER MUST COMPLETE HIS/HER OWN FORM IN ORDER TO GET HIS/HER APPLICATION. The estimated average time to complete this submission is 15 minutes per respondent.`,
            fr: `AVIS DE NON-RESPONSABILITÉ: Sur ce site Web, vous pouvez remplir le formulaire de demande d'autorisation de voyage électronique (AVE) et imprimer le formulaire de demande d'AVE, requis pour demander un visa pour le Canada. CHAQUE VOYAGEUR DOIT REMPLIR SON PROPRE FORMULAIRE POUR OBTENIR SA DEMANDE. Le temps moyen estimé pour terminer cette soumission est de 15 minutes par répondant.`,
            it: `DISCLAIMER: Su questo sito Web è possibile compilare il modulo di domanda di autorizzazione di viaggio elettronica (eTA) e stampare il modulo di domanda eTA, necessario per richiedere un visto per il Canada. OGNI VIAGGIATORE DEVE COMPLETARE IL SUO / IL SUO PROPRIO MODULO PER OTTENERE IL SUO / LA SUA DOMANDA. Il tempo medio stimato per completare questa presentazione è di 15 minuti per rispondente.`,
            de: `HAFTUNGSAUSSCHLUSS: Auf dieser Website können Sie das Formular zur Beantragung einer elektronischen Reisegenehmigung (eTA) ausfüllen und das für die Beantragung eines Visums für Kanada erforderliche eTA-Antragsformular ausdrucken. JEDER REISENDER MUSS SEIN EIGENES FORMULAR AUSFÜLLEN, UM SEINEN ANTRAG ZU ERHALTEN. Die geschätzte durchschnittliche Zeit, um diese Einreichung abzuschließen, beträgt 15 Minuten pro Befragter.`,
            es: `DESCARGO DE RESPONSABILIDAD: en este sitio web puede completar la Solicitud de un formulario de Autorización Electrónica de Viaje (eTA) e imprimir el formulario de solicitud de eTA, requerido para solicitar una visa para Canadá. CADA VIAJERO DEBE COMPLETAR SU PROPIO FORMULARIO PARA OBTENER SU SOLICITUD. El tiempo promedio estimado para completar este envío es de 15 minutos por encuestado.`
        },
        isRepresentative: {
            en: `Are you applying on behalf of someone?`,
            fr: `Êtes-vous une demande de la part de quelqu'un?`,
            es: `Está usted solicitando en nombre de alguien?`,
            de: `Bewerben Sie sich im Auftrag von jemand?`,
            it: `Si candida per conto di qualcuno?`,
        },
        isApplyingOnBehalfOfMinorChild: {
            en: `Are you applying on behalf of a minor child?`,
            fr: `Êtes-vous une demande au nom d'un enfant mineur?`,
            es: `Está usted solicitando en nombre de un menor de edad?`,
            de: `Bewerben Sie sich im Namen eines minderjährigen Kindes?`,
            it: `Si candida per conto di un minore?`,
        },
    },
    step_representative: {
        section_title: {
            en: `Parent/guardian or representative details`,
            fr: `Parent/tuteur ou le représentant de détails`,
            es: `Padre/madre / tutor o representante detalles`,
            de: `Elternteil/Vormund oder Vertreter details`,
            it: `Genitore/tutore o rappresentante dettagli`,
        },
        representativeRelationship: {
            en: `I am`,
            fr: `Je suis`,
            es: `Estoy`,
            de: `Ich bin`,
            it: `Io sono`,
        },
        representativeCompensated: {
            en: `Are you being paid to represent the applicant and complete the form on their behalf?`,
            fr: `Êtes-vous payé pour représenter le demandeur et de remplir le formulaire sur leur nom?`,
            es: `Están siendo pagados para representar al solicitante y complete el formulario en su nombre?`,
            de: `Werden Sie dafür bezahlt, der den Antragsteller vertritt und füllen Sie das Formular auf Ihren Namen?`,
            it: `Sei stato pagato per rappresentare il richiedente e completare il form sul loro conto?`,
        },
        familyName: {
            en: `Surname(s) / last name(s)`,
            fr: `Nom(s) / prénom(s)`,
            es: `Apellido(s) / apellido(s)`,
            de: `Nachname(N) / Nachname(N)`,
            it: `Cognome(i) / cognome(i)`,
        },
        firstName: {
            en: `Given name(s) / first name(s)`,
            fr: `Prénom(s) / prénom(s)`,
            es: `Nombre(s) / nombre(s)`,
            de: `Vorname(N) / first name(s)`,
            it: `Nome(i) / nome(i)`,
        },
        membershipIdNumber: {
            en: `Membership ID number`,
            fr: `L'adhésion numéro d'identification`,
            es: `Número de IDENTIFICACIÓN de membresía`,
            de: `Mitgliedschaft-ID-Nummer`,
            it: `Numero di matricola`,
        },
        province: {
            en: `Which province or territory?`,
            fr: `La province ou le territoire?`,
            es: `Que provincia o territorio?`,
            de: `Die Provinz oder Territorium?`,
            it: `Che la provincia o il territorio?`,
        },
        organizationName: {
            en: `Name of firm, organization`,
            fr: `Nom de l'entreprise, de l'organisation`,
            es: `Nombre de la empresa, organización`,
            de: `Name der Firma, Organisation`,
            it: `Nome di azienda, organizzazione`,
        },
        mailingAddress: {
            en: `Mailing address`,
            fr: `Adresse postale`,
            es: `Dirección de correo`,
            de: `Postanschrift`,
            it: `Indirizzo postale`,
        },
        phoneNumber: {
            en: `Telephone number`,
            fr: `Le numéro de téléphone`,
            es: `Número de teléfono`,
            de: `Telefonnummer`,
            it: `Il numero di telefono`,
        },
        faxNumber: {
            en: `Fax number`,
            fr: `Numéro de Fax`,
            es: `Número de Fax`,
            de: `Fax-Nummer`,
            it: `Numero di Fax`,
        },
        emailAddress: {
            en: `Email address`,
            fr: `Adresse Email`,
            es: `Dirección de correo electrónico`,
            de: `E-Mail-Adresse`,
            it: `Indirizzo e-mail`,
        },
        postalCodeZip: {
            en: `Postal code`,
            fr: `Code Postal`,
            es: `Código Postal`,
            de: `PLZ`,
            it: `Codice postale`,
        },
        declareContactAndInformationIsTruthy: {
            label: {
                en: `Representative's declaration`,
                fr: `Représentant de la déclaration`,
                es: `Representante de la declaración`,
                de: `Vertreter in der Erklärung`,
                it: `Rappresentante dichiarazione del`,
            },
            extra: {
                en: `I declare that my contact and personal information above is truthful, complete and correct.`,
                fr: `Je déclare que mes informations personnelles et de contact ci-dessus sont véridiques, complets et exacts.`,
                es: `Declaro que mi contacto personal y la información anterior es verdadera, completa y correcta.`,
                de: `Ich erkläre, dass meine Kontakt-und persönlichen Informationen über ist wahrheitsgemäß, vollständig und richtig sind.`,
                it: `Dichiaro che le mie informazioni personali e di contatto sopra sono veritiere, complete e corrette.`,
            },
        },
        understandAndAccept: {
            label: {
                en: `Representative's authorization`,
                fr: `Représentant de l'autorisation`,
                es: `Representante de la autorización de`,
                de: `Vertreter Genehmigung`,
                it: `Rappresentante dell'autorizzazione`,
            },
            extra: {
                en: `I understand and accept that I am the person appointed by the applicant to conduct business on the applicant or sponsor's behalf with Immigration, Refugees and Citizenship Canada and the Canada Border Services Agency.`,
                fr: `Je comprends et j'accepte que je suis la personne désignée par le demandeur à la conduite des affaires sur le demandeur ou du commanditaire nom de l'Immigration, des Réfugiés et de la Citoyenneté du Canada et l'Agence canadienne des Services Frontaliers.`,
                es: `Entiendo y acepto que soy la persona designada por el solicitante para llevar a cabo negocios en el solicitante o del patrocinador nombre con la Inmigración, los Refugiados y Ciudadanía de Canadá y de la Agencia de Servicios Fronterizos de Canadá.`,
                de: `Ich verstehe und akzeptiere, dass ich bin die person, die ernannt durch die Klägerin die Geschäfte über den Antragsteller oder sponsor-Namen mit der Einwanderung, Flüchtlingen und Bürgerschaft Canada und der Canada Border Services Agency.`,
                it: `Capisco e accetto che io sono la persona nominata dal richiedente ad effettuare il richiedente o di sponsor conto, Immigrazione, Rifugiati e Cittadinanza Canada e il Canada Border Services Agency.`,
            },
        },
    },
    step_prerequisite: {
        section_title: {
            en: `Complete the application form (Prerequisite)`,
            fr: `Remplir le formulaire de demande (Prérequis)`,
            es: `Completar el formulario de solicitud (Prerrequisito)`,
            de: `Füllen Sie das Antragsformular aus (Voraussetzung)`,
            it: `Completa il modulo di domanda (Prerequisito)`,
        },
        travelDocumentType: {
            en: `What travel document do you plan to use to travel to Canada?`,
            fr: `Ce document de voyage avez-vous l'intention d'utiliser pour voyager au Canada?`,
            es: `¿Qué documento de viaje ¿piensa utilizar para viajar a Canadá?`,
            de: `Was Reisedokument planen Sie Reisen nach Kanada?`,
            it: `Quale documento di viaggio si intende utilizzare per il viaggio in Canada?`,
        },
        countryOfCitizenship: {
            label: {
                en: `Select the code that matches the one on your passport.`,
                fr: `Sélectionnez le code qui correspond à celle de votre passeport.`,
                es: `Seleccione el código que coincide con el de su pasaporte.`,
                de: `Wählen Sie den code, der übereinstimmt, die auf Ihrem Reisepass.`,
                it: `Selezionare il codice che corrisponde a quello sul passaporto.`,
            },
            extra: {
                en: `Find this code on your passport information page - see the field named "Code", "Issuing country", "Authority" or "Country code".`,
                fr: `Trouver ce code sur votre passeport page d'information - voir le champ nommé "Code", "pays d'Émission", "Autorité" ou "code Pays".`,
                es: `Encontrar este código en tu pasaporte de la página de información - ver el campo denominado "Código", "país Emisor", la "Autoridad" o "código de País".`,
                de: `Finden diesen code in Ihrem Reisepass Informationen finden Sie unter dem Feld "Code", "Herkunftsland", "Autorität" oder "Country code".`,
                it: `Questo codice sul tuo passaporto, informazioni pagina - vedere il campo denominato "Codice", "paese di Emissione", "Autorità" o "codice Paese".`,
            },
        },
        hasIsraeliNationalPassport: {
            en: `For this trip, will you use a national Israeli passport?`,
            fr: `Pour ce voyage, allez-vous utiliser un national passeport Israélien?`,
            es: `Para este viaje, se utiliza un nacional Israelí pasaporte?`,
            de: `Für diese Reise, werden Sie eine nationale israelischen Pass?`,
            it: `Per questo viaggio, di utilizzare nazionale di passaporto Israeliano?`,
        },
        passportNotedNationality: {
            label: {
                en: `What is the nationality noted on this passport?`,
                fr: `Quelle est la nationalité de noter sur ce passeport?`,
                es: `¿Cuál es la nacionalidad observó en este pasaporte?`,
                de: `Was ist die Nationalität festgestellt, über diesen Pass?`,
                it: `Qual è la nazionalità notato in questo passaporto?`,
            },
            extra: {
                en: `See "Nationality" on your passport information page`,
                fr: `Voir "Nationalité" sur votre passeport page d'informations`,
                es: `Consulte la "Nacionalidad" en su página de información del pasaporte`,
                de: `Unter "Nationalität" auf Ihren Reisepass Informationen Seite`,
                it: `Vedere "Nazionalità" sul passaporto pagina di informazioni`,
            },
        },
        isPermanentResidentOfUSAndHaveProofOfPermResidence: {
            en: `Are you a lawful permanent resident of the United States with a valid U.S. Citizenship and Immigration Services (USCIS) number?`,
            fr: `Êtes-vous un résident permanent légal des États-unis avec une pièce US Citizenship and Immigration Services (USCIS) nombre?`,
            es: `¿Es usted un residente permanente legal de los Estados unidos con una válida de los estados UNIDOS de Ciudadanía y Servicios de Inmigración (USCIS) número?`,
            de: `Sind Sie ein rechtmäßigen ständigen Wohnsitz in den Vereinigten Staaten mit einem gültigen US-Staatsbürgerschaft-und Immigration-Services (USCIS) Nummer???`,
            it: `Sei un residente permanente degli Stati Uniti, con un valido UNITI Cittadinanza e Servizi Immigrazione (USCIS) numero?`,
        },
        usaResidentCardNumber: {
            en: `United States lawful permanent resident USCIS number`,
            fr: `États-unis résident permanent légal de l'USCIS nombre`,
            es: `Estados unidos, residente permanente legal de USCIS número`,
            de: `Vereinigten Staaten rechtmäßigen ständigen Wohnsitz USCIS Nummer`,
            it: `Stati uniti di residente permanente, USCIS numero`,
        },
        usaResidentCardNumberReEnter: {
            en: `United States lawful permanent resident alien registration card (Green Card) number (re-enter)`,
            fr: `États-unis résident permanent légal inscription au registre des étrangers (carte Verte) numéro (ré-entrée)`,
            es: `Estados unidos de residente legal permanente, tarjeta de registro de extranjero (Tarjeta Verde) número (volver a entrar)`,
            de: `Vereinigten Staaten rechtmäßiger permanent resident alien registration card (Green Card) Zahl (re-enter)`,
            it: `Stati uniti di residente permanente, alien registration card (Carta Verde) numero (re-invio)`,
        },
        usaResidentCardExpiryDate: {
            en: `Date of expiry`,
            fr: `Date d'expiration`,
            es: `Fecha de caducidad`,
            de: `Ablauf`,
            it: `Data di scadenza`,
        },
        hasPassportIssuedByMFA: {
            en: `For this trip, will you use a passport issued by the Ministry of Foreign Affairs in Taiwan that includes your personal identification number?`,
            fr: `Pour ce voyage, allez-vous utiliser un passeport délivré par le Ministère des Affaires Étrangères à Taïwan qui inclut votre numéro d'identification personnel?`,
            es: `Para este viaje, se puede usar un pasaporte expedido por el Ministerio de Asuntos Exteriores de Taiwán, que incluye su número de identificación personal?`,
            de: `Für diese Reise benötigen Sie einen Reisepass, ausgestellt durch das Ministerium für Auswärtige Angelegenheiten in Taiwan, die Ihre persönliche Identifikationsnummer?`,
            it: `Per questo viaggio, di utilizzare un passaporto rilasciato dal Ministero degli Affari Esteri di Taiwan che include il tuo numero di identificazione personale?`,
        },
        taiwanIDNumber: {
            en: `Taiwan personal identification number`,
            fr: `Taiwan numéro d'identification personnel`,
            es: `Taiwan número de identificación personal`,
            de: `Taiwan-persönliche Identifikationsnummer`,
            it: `Taiwan numero di identificazione personale`,
        },
        taiwanIDNumberReEnter: {
            en: `Taiwan personal identification number (re-enter)`,
            fr: `Taiwan numéro d'identification personnel (ré-entrée)`,
            es: `Taiwan número de identificación personal (re-enter)`,
            de: `Taiwan persönlichen Identifikationsnummer (re-enter)`,
            it: `Taiwan numero di identificazione personale (re-invio)`,
        },
        hasEPassport: {
            en: `Will you use an electronic passport for this trip?`,
            fr: `Allez-vous utiliser un passeport électronique pour ce voyage?`,
            es: `Se puede usar un pasaporte electrónico para este viaje?`,
            de: `Verwenden Sie einen elektronischen Reisepass für diese Reise?`,
            it: `Verrà utilizzato un passaporto elettronico per questo viaggio?`,
        },
    },
    step_passport: {
        section_title: {
            en: `Passport details of applicant`,
            fr: `Les détails du passeport du demandeur`,
            es: `Los datos del pasaporte del solicitante`,
            de: `Reisepass des Antragstellers`,
            it: `Dettagli del passaporto del richiedente`,
        },
        passportNumber: {
            label: {
                en: `Passport number`,
                fr: `Numéro de passeport`,
                es: `Número de pasaporte`,
                de: `Pass-Nummer`,
                it: `Il numero di passaporto`,
            },
            extra: {
                en: `Enter the passport number exactly as it appears on the passport information page.`,
                fr: `Entrez le numéro du passeport, exactement comme il apparaît sur le passeport de l'information de la page.`,
                es: `Introducir el número de pasaporte, exactamente como aparece en el pasaporte de la página de información.`,
                de: `Geben Sie die Nummer des Reisepasses genau so, wie es scheint, auf die passport-Informationen Seite.`,
                it: `Immettere il numero di passaporto, esattamente come appare sul passaporto pagina di informazioni.`,
            },
        },
        passportNumberReEnter: {
            label: {
                en: `Passport number`,
                fr: `Numéro de passeport`,
                es: `Número de pasaporte`,
                de: `Pass-Nummer`,
                it: `Il numero di passaporto`,
            },
            extra: {
                en: `You cannot copy and paste into this field.`,
                fr: `Vous ne pouvez pas copier et coller dans ce champ.`,
                es: `Usted no puede copiar y pegar en este campo.`,
                de: `Sie können nicht kopieren und einfügen in das Feld.`,
                it: `Non è possibile copiare e incollare in questo campo.`,
            },
        },
        lastName: {
            label: {
                en: `Surname(s) / last name(s)`,
                fr: `Nom(s) / prénom(s)`,
                es: `Apellido(s) / apellido(s)`,
                de: `Nachname(N) / Nachname(N)`,
                it: `Cognome(i) / cognome(i)`,
            },
            extra: {
                en: `Please enter exactly as shown on your passport or identity document.`,
                fr: `Veuillez saisir exactement comme indiqué sur votre passeport ou document d'identité.`,
                es: `Por favor, introduzca exactamente como aparece en su pasaporte o documento de identidad.`,
                de: `Bitte geben Sie genau an, wie er auf Ihrem Reisepass oder Personalausweis.`,
                it: `Si prega di inserire esattamente come indicato sul passaporto o documento di identità.`,
            },
        },
        firstName: {
            label: {
                en: `Given name(s) / first name(s)`,
                fr: `Prénom(s) / prénom(s)`,
                es: `Nombre(s) / nombre(s)`,
                de: `Vorname(N) / first name(s)`,
                it: `Nome(i) / nome(i)`,
            },
            extra: {
                en: `Please enter exactly as shown on your passport or identity document.`,
                fr: `Veuillez saisir exactement comme indiqué sur votre passeport ou document d'identité.`,
                es: `Por favor, introduzca exactamente como aparece en su pasaporte o documento de identidad.`,
                de: `Bitte geben Sie genau an, wie er auf Ihrem Reisepass oder Personalausweis.`,
                it: `Si prega di inserire esattamente come indicato sul passaporto o documento di identità.`,
            },
        },
        dob: {
            en: `Date of birth`,
            fr: `Date de naissance`,
            es: `Fecha de nacimiento`,
            de: `Geburtsdatum`,
            it: `Data di nascita`,
        },
        gender: {
            en: `Gender`,
            fr: `Sexe`,
            es: `Género`,
            de: `Geschlecht`,
            it: `Genere`,
        },
        maritalStatus: {
            en: `Marital status`,
            fr: `État matrimonial`,
            es: `Estado civil`,
            de: `Familienstand`,
            it: `Stato civile`,
        },
        countryOfBirth: {
            en: `Country/territory of birth`,
            fr: `Pays/territoire de naissance`,
            es: `País/territorio de nacimiento`,
            de: `Land/Territorium der Geburt`,
            it: `Paese di nascita`,
        },
        cityTownOfBirth: {
            en: `City/town of birth`,
            fr: `Ville de naissance`,
            es: `Ciudad/pueblo de nacimiento`,
            de: `Stadt/Ort der Geburt`,
            it: `Città/paese di nascita`,
        },
        issueDate: {
            en: `Date of issue of passport`,
            fr: `Date d'émission du passeport`,
            es: `Fecha de emisión de pasaporte`,
            de: `Ausstellungsdatum des Reisepasses`,
            it: `Data di rilascio del passaporto`,
        },
        expiryDate: {
            en: `Date of expiry of passport`,
            fr: `Date d'expiration du passeport`,
            es: `La fecha de vencimiento de pasaporte`,
            de: `Datum des Ablaufs der Gültigkeit des Passes`,
            it: `Data di scadenza del passaporto`,
        },
    },
    step_personal: {
        section_title: {
            en: `Personal details of applicant`,
            fr: `Coordonnées personnelles du demandeur`,
            es: `Datos personales del solicitante`,
            de: `Persönliche Angaben des Antragstellers`,
            it: `Dati personali del richiedente`,
        },
        additionalCitizenships: {
            en: `Indicate which countries/territories you are a citizen of.`,
            fr: `Indiquer les pays/territoires que vous êtes un citoyen de l'.`,
            es: `Indican que los países/territorios que usted es un ciudadano de.`,
            de: `Angeben, welche Länder/Gebiete sind Sie Bürger.`,
            it: `Indicare quali paesi/territori si sono un cittadino di.`,
        },
        hasPreviouslyAppliedToCanada: {
            en: `Have you ever applied for or obtained a visa, an eTA or a permit to visit, live, work or study in Canada?`,
            fr: `Avez-vous déjà demandé ou obtenu un visa, un visa ou un permis de visite, de vivre, de travailler ou d'étudier au Canada?`,
            es: `¿Alguna vez has solicitado u obtenido una visa, un eTA o un permiso para visitar, vivir, trabajar o estudiar en Canadá?`,
            de: `Haben Sie jemals beantragt oder erhalten ein Visum, das eTA-Visum oder eine Genehmigung zu besuchen, Leben, arbeiten oder studieren in Kanada?`,
            it: `Avete mai chiesto o ottenuto un visto, un eTA o di un permesso di visitare, vivere, lavorare o studiare in Canada?`,
        },
        uci: {
            en: `Unique client identifier (UCI) / Previous Canadian visa, eTA or permit number (optional)`,
            fr: `Unique identifiant du client (UCI) / Précédent visa Canadien, l'eTA ou de numéro de permis (en option)`,
            es: `Único identificador de cliente (UCI) Anterior / visa Canadiense, eTA o número de permiso (opcional)`,
            de: `Eindeutige client-id (UCI) / Vorherigen Kanadischen visa -, eTA-oder Zulassungsnummer (optional)`,
            it: `Unico identificatore client (UCI) / Precedente Canadese di visto, di eTA o di permesso di numero (opzionale)`,
        },
        uciReEnter: {
            en: `Unique client identifier (UCI) / Previous Canadian visa, eTA or permit number (re-enter)`,
            fr: `Unique identifiant du client (UCI) / Précédent visa Canadien, l'eTA ou de numéro de permis de (re-entrée)`,
            es: `Único identificador de cliente (UCI) Anterior / visa Canadiense, eTA o número de permiso (volver a entrar)`,
            de: `Eindeutige client-id (UCI) / Vorherigen Kanadischen visa -, eTA-oder Zulassungsnummer (re-enter)`,
            it: `Unico identificatore client (UCI) / Precedente Canadese di visto, di eTA o di permesso di numero (re-invio)`,
        },
    },
    step_employment: {
        section_title: {
            en: `Employment information`,
            fr: `D'information sur l'emploi`,
            es: `Información de empleo`,
            de: `Beschäftigung Informationen`,
            it: `Informazioni di lavoro`,
        },
        occupation: {
            label: {
                en: `Occupation`,
                fr: `L'Occupation`,
                es: `Ocupación`,
                de: `Besetzung`,
                it: `Occupazione`,
            },
            extra: {
                en: `Select the option that best describes your current employment situation.`,
                fr: `Sélectionnez l'option qui décrit le mieux votre situation d'emploi actuelle.`,
                es: `Seleccione la opción que mejor describe su situación laboral actual.`,
                de: `Wählen Sie die option, die am besten beschreibt Ihre derzeitige Beschäftigungssituation.`,
                it: `Selezionare l'opzione che meglio descrive la tua occupazione attuale situazione.`,
            },
        },
        title: {
            label: {
                en: `Job title`,
                fr: `Titre de l'emploi`,
                es: `Título del trabajo`,
                de: `Job-Titel`,
                it: `Titolo di lavoro`,
            },
            extra: {
                en: `Select the option that best describes your job.`,
                fr: `Sélectionnez l'option qui décrit le mieux votre travail.`,
                es: `Seleccione la opción que mejor describe su trabajo.`,
                de: `Wählen Sie die option, die am besten beschreibt, Ihren job.`,
                it: `Selezionare l'opzione che meglio descrive il vostro lavoro.`,
            },
        },
        companyEmployerSchoolFacilityName: {
            en: `Name of employer or school, as appropriate.`,
            fr: `Nom de l'employeur ou de l'école, selon le cas.`,
            es: `Nombre de la empresa o de la escuela, según corresponda.`,
            de: `Name des Arbeitgebers oder der Schule, als angemessen.`,
            it: `Nome del datore di lavoro o la scuola, come appropriato.`,
        },
        country: {
            en: `Country/territory`,
            fr: `Pays/territoire`,
            es: `País/territorio`,
            de: `Land/Gebiet`,
            it: `Paese/territorio`,
        },
        province: {
            en: `Province/state`,
            fr: `Province/état`,
            es: `Provincia/estado`,
            de: `Provinz/Staat`,
            it: `Provincia/stato`,
        },
        city: {
            en: `City/town`,
            fr: `Ville/village`,
            es: `Ciudad/pueblo`,
            de: `Stadt/Ort`,
            it: `Città/town`,
        },
        fromDateYear: {
            en: `Since what year?`,
            fr: `Depuis quelle année?`,
            es: `Desde qué año?`,
            de: `Seit welchem Jahr?`,
            it: `Dal momento che anno?`,
        },
    },
    step_contact: {
        section_title: {
            en: `Contact information`,
            fr: `Les informations de Contact`,
            es: `Información de contacto`,
            de: `Kontakt-Informationen`,
            it: `Informazioni di contatto`,
        },
        languageOfPreference: {
            en: `Preferred language to contact you `,
            fr: `Langue préférée pour vous contacter `,
            es: `Idioma preferido en contacto con usted `,
            de: `Bevorzugte Sprache, um Sie zu Kontaktieren `,
            it: `Lingua preferita per contattare l'utente `,
        },
        emailAddress: {
            label: {
                en: `Email address`,
                fr: `Adresse Email`,
                es: `Dirección de correo electrónico`,
                de: `E-Mail-Adresse`,
                it: `Indirizzo e-mail`,
            },
            extra: {
                en: `Please enter a valid email address. It will be used to contact you about your application.`,
                fr: `Veuillez entrer une adresse email valide. Il sera utilisé pour vous contacter à propos de votre demande.`,
                es: `Por favor, introduzca una dirección válida de correo electrónico. Será utilizada para contactar con usted acerca de su aplicación.`,
                de: `Bitte geben Sie eine gültige E-Mail-Adresse. Es wird verwendet, um Kontakt mit Ihnen über Ihre Anwendung.`,
                it: `Si prega di inserire un indirizzo email valido. Saranno utilizzati per contattare l'utente circa la vostra applicazione.`,
            },
        },
        emailAddressReEnter: {
            label: {
                en: `Email address (re-enter)`,
                fr: `Adresse e-mail (ré-entrée)`,
                es: `Dirección de correo electrónico (volver a entrar)`,
                de: `E-Mail-Adresse (re-enter)`,
                it: `Indirizzo e-mail (re-invio)`,
            },
            extra: {
                en: `You cannot copy and paste into this field.`,
                fr: `Vous ne pouvez pas copier et coller dans ce champ.`,
                es: `Usted no puede copiar y pegar en este campo.`,
                de: `Sie können nicht kopieren und einfügen in das Feld.`,
                it: `Non è possibile copiare e incollare in questo campo.`,
            },
        },
    },
    step_residential: {
        section_title: {
            en: `Residential address`,
            fr: `Adresse de résidence`,
            es: `Dirección residencial`,
            de: `Wohn-Adresse`,
            it: `Indirizzo di residenza`,
        },
        section_description: {
            en: `Enter your permanent home address. Do not enter an address where you live temporarily.`,
            fr: `Entrez votre adresse de domicile permanent. Ne pas entrer une adresse où vous vivez temporairement.`,
            es: `Ingresa tu dirección permanente. No introduzca una dirección donde usted vive temporalmente.`,
            de: `Geben Sie Ihre Feste Adresse. Geben Sie nicht eine Adresse, wo Sie Leben vorübergehend.`,
            it: `Inserisci il tuo indirizzo di residenza permanente. Non inserire un indirizzo in cui si vive temporaneamente.`,
        },
        aptUnit: {
            en: `Apartment/unit number (if applicable)`,
            fr: `Appartement/numéro d'unité (si applicable)`,
            es: `Apartamento/unidad (si aplica)`,
            de: `Apartment/unit-Nummer (falls zutreffend)`,
            it: `Appartamento/numero di unità (se applicabile)`,
        },
        streetNo: {
            en: `Street/civic number or house name`,
            fr: `Rue/numéro ou nom de maison`,
            es: `Calle/cívica número o nombre de la casa`,
            de: `Street/civic Nummer oder Haus name`,
            it: `Via/numero civico di casa o del nome`,
        },
        streetAddress: {
            en: `Street address/name`,
            fr: `Adresse/nom`,
            es: `Dirección/nombre de la`,
            de: `Adresse/name`,
            it: `Indirizzo/nome`,
        },
        streetAddressAlt: {
            en: `Street address/name line 2 (if applicable)`,
            fr: `Adresse/nom de la ligne 2 (si applicable)`,
            es: `Dirección/nombre de la línea 2 (si es aplicable)`,
            de: `Anschrift/name Zeile 2 (falls zutreffend)`,
            it: `Indirizzo/nome linea 2 (se applicabile)`,
        },
        city: {
            en: `City/town`,
            fr: `Ville/village`,
            es: `Ciudad/pueblo`,
            de: `Stadt/Ort`,
            it: `Città/town`,
        },
        country: {
            en: `Country/territory`,
            fr: `Pays/territoire`,
            es: `País/territorio`,
            de: `Land/Gebiet`,
            it: `Paese/territorio`,
        },
        district: {
            en: `District/region`,
            fr: `District/région`,
            es: `Distrito/región`,
            de: `Bezirk/region`,
            it: `Distretto/regione`,
        },
        state: {
            en: `Province/state`,
            fr: `Province/état`,
            es: `Provincia/estado`,
            de: `Provinz/Staat`,
            it: `Provincia/stato`,
        },
        zipCode: {
            en: `ZIP code`,
            fr: `Code POSTAL`,
            es: `El código POSTAL de`,
            de: `ZIP code`,
            it: `C.a.p.`,
        },
    },
    step_travel: {
        section_title: {
            en: `Travel information`,
            fr: `Informations de voyage`,
            es: `Información de viajes`,
            de: `Reise-Informationen`,
            it: `Informazioni di viaggio`,
        },
        isTravelDateKnown: {
            label: {
                en: `Do you know when you will travel to Canada?`,
                fr: `Savez-vous quand vous allez voyager au Canada?`,
                es: `¿Sabe usted cuando usted va a viajar a Canadá?`,
                de: `Wissen Sie, wenn Sie Reisen nach Kanada?`,
                it: `Sapete quando si metterà in viaggio per il Canada?`,
            },
            extra: {
                en: `This information may help us to process your application. If you do not know when you will travel to Canada, please select "no".`,
                fr: `Cette information peut nous aider à traiter votre demande. Si vous ne savez pas quand vous voyagez au Canada, veuillez sélectionner "non".`,
                es: `Esta información puede ayudarnos a procesar su solicitud. Si usted no sabe cuando va a viajar a Canadá, por favor seleccione "no".`,
                de: `Diese Informationen helfen uns, um Ihre Anwendung zu verarbeiten. Wenn Sie nicht wissen, Wann Sie Reisen nach Kanada, bitte wählen Sie "Nein".`,
                it: `Queste informazioni possono aiutare a elaborare la vostra applicazione. Se non si sa quando si farà un viaggio in Canada, si prega di selezionare "no".`,
            },
        },
        travelDate: {
            label: {
                en: `Do you know when you will travel to Canada?`,
                fr: `Savez-vous quand vous allez voyager au Canada?`,
                es: `¿Sabe usted cuando usted va a viajar a Canadá?`,
                de: `Wissen Sie, wenn Sie Reisen nach Kanada?`,
                it: `Sapete quando si metterà in viaggio per il Canada?`,
            },
            extra: {
                en: `If you don't know, you may enter an approximate date.`,
                fr: `Si vous ne savez pas, vous pouvez saisir une date approximative.`,
                es: `Si usted no sabe, usted puede ingresar una fecha aproximada.`,
                de: `Wenn Sie nicht wissen, können Sie ein Ungefähres Datum.`,
                it: `Se non si conosce, è possibile immettere una data approssimativa.`,
            },
        },
        travelTime: {
            en: `Please enter the time your flight to Canada will depart`,
            fr: `Veuillez entrer l'heure de votre vol à destination du Canada partira`,
            es: `Por favor, introduzca el tiempo de tu vuelo a Canadá partirá`,
            de: `Bitte geben Sie die Uhrzeit Ihres Fluges nach Kanada fahren`,
            it: `Si prega di inserire il tempo di volo per il Canada partirà`,
        },
        travelDateTimeHour: {
            en: `Hour`,
            fr: `Heure`,
            es: `Hora`,
            de: `Stunde`,
            it: `Ora`,
        },
        travelDateTimeMinute: {
            en: `Minute`,
            fr: `Minutes`,
            es: `Minutos`,
            de: `Minute`,
            it: `Minuti`,
        },
        travelDateTimeTimezone: {
            en: `Timezone`,
            fr: `Fuseau horaire`,
            es: `La zona horaria`,
            de: `Timezone`,
            it: `Fuso orario`,
        },
    },
    step_background: {
        section_title: {
            en: `Background Questions`,
            fr: `Questions De Fond`,
            es: `Fondo Preguntas`,
            de: `Hintergrund Fragen`,
            it: `Sfondo Domande`,
        },
        refusedVisaOrPermitOrDeniedEntryToCanada: {
            en: `Have you ever been refused a visa or permit, denied entry to, or ordered to leave Canada or any other country/territory?`,
            fr: `Avez-vous déjà refusé un visa ou d'un permis, refuser l'accès à, ou l'ordre de quitter le Canada ou tout autre pays/territoire?`,
            es: `¿Alguna vez has sido negado una visa o permiso denegado la entrada, o la orden de salir de Canadá o cualquier otro país o territorio?`,
            de: `Haben Sie schon einmal weigerte sich, ein Visum oder eine Aufenthaltserlaubnis, die Einreise verweigert wurde, oder bestellt zu verlassen, in Kanada oder jedem anderen Land/Gebiet?`,
            it: `Sei mai stato rifiutato un visto o di un permesso negato l'ingresso, o ordinato di lasciare il Canada o in qualsiasi altro paese/territorio?`,
        },
        refusedVisaOrPermitOrDeniedEntryToCanadaDetails: {
            en: `For each refusal, please indicate the country that refused you a visa or permit, or denied you entry, as well as the reasons provided to you by the country.`,
            fr: `Pour chaque cas de refus, veuillez indiquer les pays qui ont refusé de vous un visa ou d'un permis, ou vous a refusé l'entrée, ainsi que les raisons fournies par le pays.`,
            es: `Para cada negativa, favor de indicar el país de que se negó una visa o permiso, o se les niega la entrada, así como las razones aducidas por el país.`,
            de: `Für jede Verweigerung, geben Sie bitte das Land, das sich weigerte, Ihnen ein Visum oder eine Arbeitserlaubnis oder verweigert Ihnen die Einreise, sowie die Gründe, die Sie von dem Land.`,
            it: `Per ogni rifiuto, siete pregati di indicare il paese che ha rifiutato un visto o di un permesso o negato l'ingresso, così come le ragioni fornite dal paese.`,
        },
        committedOrArrestedOrChargedOrConvictedOfCriminalOffenceAnywhere: {
            en: `Have you ever committed, been arrested for, been charged with or convicted of any criminal offence in any country/territory?`,
            fr: `Avez-vous déjà commis, été arrêté pour, été accusé ou déclaré coupable d'une infraction pénale dans tous les pays/territoire?`,
            es: `Alguna vez ha cometido o ha sido arrestado sido acusado o condenado por cualquier delito en cualquier país o territorio?`,
            de: `Haben Sie jemals begangen, wurde verhaftet, angeklagt oder verurteilt jede straftat, in jedem Land/Gebiet?`,
            it: `Hai mai commesso, è stato arrestato, accusato o condannato per un reato in qualsiasi paese/territorio?`,
        },
        committedOrArrestedOrChargedOrConvictedOfCriminalOffenceAnywhereDetails: {
            en: `For each arrest, charge, or conviction, please indicate where (city, country), when (month/year), the nature of the offence, and the sentence.`,
            fr: `Pour chaque arrestation, l'accusation ou condamnation, veuillez indiquer où (ville, pays), quand (mois/année), la nature de l'infraction et de la peine.`,
            es: `Para cada detención, cargo, o condena, por favor indicar dónde (ciudad, país), cuando (mes/año), la naturaleza de la infracción, y la frase.`,
            de: `Für jede Verhaftung, Anklage, oder Verurteilung, bitte geben Sie an, wo (Stadt, Land), wenn (Monat/Jahr), der Art der straftat und der Strafe.`,
            it: `Per ogni arresto, la carica, o convinzione, si prega di indicare dove (città, paese), quando (mese/anno), la natura del reato, e la sentenza.`,
        },
        inThePastTwoYearsWereYouDiagnosedOrInCloseContactWithTuberculosis: {
            en: `In the past two years, were you diagnosed with tuberculosis or have you been in close contact with a person with tuberculosis?`,
            fr: `Dans les deux dernières années, avez-vous été diagnostiqué avec la tuberculose ou avez-vous été en contact étroit avec une personne souffrant de tuberculose?`,
            es: `En los últimos dos años, fueron diagnosticados con tuberculosis o ha estado en contacto cercano con una persona con tuberculosis?`,
            de: `In den vergangenen zwei Jahren, wurden Sie diagnostiziert mit Tuberkulose oder haben Sie in engen Kontakt mit einer person mit Tuberkulose?`,
            it: `Negli ultimi due anni, vi sono stati diagnosticati con la tubercolosi o è stato in stretto contatto con una persona con tubercolosi?`,
        },
        isYourContactWithTuberculosisTheResultOfBeingAHeathCareWorker: {
            en: `Is your contact with tuberculosis the result of being a health care worker?`,
            fr: `Est votre contact avec la tuberculose du fait d'un travailleur de soins de santé?`,
            es: `Es su contacto con la tuberculosis el resultado de ser un trabajador de la salud?`,
            de: `Ist der Kontakt mit Tuberkulose das Ergebnis von einem Beschäftigten im Gesundheitswesen?`,
            it: `È il contatto con la tubercolosi causa di un operatore sanitario?`,
        },
        haveYouEverBeenDiagnosedWithTuberculosis: {
            en: `Have you ever been diagnosed with tuberculosis?`,
            fr: `Avez-vous déjà reçu un diagnostic de tuberculose?`,
            es: `¿Alguna vez ha sido diagnosticado con tuberculosis?`,
            de: `Haben Sie schon einmal diagnostiziert mit Tuberkulose?`,
            it: `Sei mai stata diagnosticata la tubercolosi?`,
        },
        doYouHaveOneOfTheseConditions: {
            en: `Have you ever been diagnosed with tuberculosis?`,
            fr: `Avez-vous déjà reçu un diagnostic de tuberculose?`,
            es: `¿Alguna vez ha sido diagnosticado con tuberculosis?`,
            de: `Haben Sie schon einmal diagnostiziert mit Tuberkulose?`,
            it: `Sei mai stata diagnosticata la tubercolosi?`,
        },
        haveOrWillHaveHealthInsuranceValidInCanadaDuringStayDetails: {
            en: `Please briefly indicate if there are additional details pertinent to your application. For example, an urgent need to travel to Canada. Provide relevant details to avoid delays in the processing of your application.`,
            fr: `Veuillez indiquer brièvement si il y a d'autres détails pertinents à votre demande. Par exemple, un besoin urgent de se rendre au Canada. Fournir les détails pertinents afin d'éviter les retards dans le traitement de votre demande.`,
            es: `Por favor indicar brevemente si hay detalles adicionales pertinentes para su aplicación. Por ejemplo, una necesidad urgente para viajar a Canadá. Proporcionar información pertinente a fin de evitar demoras en el procesamiento de su solicitud.`,
            de: `Bitte kurz angeben, ob gibt es zusätzliche details, die relevant für Ihre Anwendung. Zum Beispiel, die dringende Notwendigkeit zu Reisen nach Kanada. Bieten Sie relevante Informationen zur Vermeidung von Verzögerungen bei der Bearbeitung Ihres Antrags.`,
            it: `Si prega di indicare brevemente se ci sono ulteriori dettagli pertinenti a la vostra applicazione. Per esempio, un bisogno urgente di viaggio per il Canada. Fornire informazioni rilevanti al fine di evitare ritardi nell'elaborazione della vostra applicazione.`,
        },
    },
    step_consent: {
        section_title: {
            en: `Declaration of Applicant`,
            fr: `Déclaration du Demandeur`,
            es: `Declaración del Solicitante`,
            de: `Erklärung des Antragstellers`,
            it: `Dichiarazione del Richiedente`,
        },
        section_description_2: {
            en: `I declare that the information I have given in this application is truthful, complete and correct.`,
            fr: `Je déclare que les renseignements que j'ai fournis dans cette demande sont véridiques, complets et exacts.`,
            es: `Declaro que la información que he proporcionado en esta solicitud es verdadera, completa y correcta.`,
            de: `Ich erkläre, dass die Informationen, die ich gegeben habe, in diesem Antrag ist wahrheitsgemäß, vollständig und richtig sind.`,
            it: `Dichiaro che le informazioni riportate nella presente domanda sono veritiere, complete e corrette.`,
        },
        section_description_3: {
            en: `I understand that misrepresentation is an offence under section 127 of the Immigration and Refugee Protection Act and may result in a finding of inadmissibility to Canada or removal from Canada.`,
            fr: `Je comprends que toute fausse déclaration constitue une infraction en vertu de l'article 127 de la loi sur l'Immigration et la Protection des Réfugiés et peut déboucher sur un constat d'interdiction de territoire au Canada ou le retrait du Canada.`,
            es: `Entiendo que la falsedad es un delito en virtud del artículo 127 de la Inmigración y Protección de Refugiados de la Ley y puede resultar en una declaración de inadmisibilidad a Canadá, o la eliminación de Canadá.`,
            de: `Ich verstehe, dass Täuschung ist eine straftat nach § 127 des Immigration and Refugee Protection Act und kann in einer Feststellung der Unzulässigkeit nach Kanada oder entfernen von Kanada.`,
            it: `Capisco che false dichiarazioni è un reato in virtù dell'articolo 127 della Immigration and Refugee Protection Act, e può comportare una dichiarazione di irricevibilità per il Canada o la rimozione dal Canada.`,
        },
        section_description_4: {
            en: `I agree that by typing my name and clicking sign, I am electronically signing my application.`,
            fr: `Je suis d'accord qu'en tapant mon nom et en cliquant sur le signe, je suis à la signature électronique de mon application.`,
            es: `Estoy de acuerdo en que escribiendo mi nombre y haciendo clic en el signo, yo soy la firma electrónica de la aplicación.`,
            de: `Ich willige ein, dass bei der Eingabe meines Namen und klicken auf anmelden, bin ich elektronisch signieren meiner Anwendung.`,
            it: `Sono d'accordo che digitando il mio nome e fare clic su firma, io la firma elettronica e la mia applicazione.`,
        },
        inAggreance: {
            label: {
                en: `I Agree`,
                fr: `Je Suis D'Accord`,
                es: `Estoy De Acuerdo`,
                de: `Ich Stimme Zu`,
                it: `Sono D'Accordo`,
            },
            extra: {
                en: `I Agree`,
                fr: `Je Suis D'Accord`,
                es: `Estoy De Acuerdo`,
                de: `Ich Stimme Zu`,
                it: `Sono D'Accordo`,
            },
        },
        fullName: {
            label: {
                en: `Signature of applicant`,
                fr: `Signature du demandeur`,
                es: `Firma del solicitante`,
                de: `Unterschrift des Antragstellers`,
                it: `Firma del richiedente`,
            },
            extra: {
                en: `To sign, enter your name as it appears on your passport.`,
                fr: `Pour signer, entrez votre nom tel qu'il apparaît sur votre passeport.`,
                es: `Para firmar, escriba su nombre tal como aparece en su pasaporte.`,
                de: `Anmelden, geben Sie Ihren Namen, wie es scheint in Ihrem Reisepass.`,
                it: `A segno, inserisci il tuo nome come appare sul passaporto.`,
            },
        },
    },
}

export default resources